### ISSUE TITLE
HEC Port is not exposed by the operator

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-operator#1]
In testing deployments with Splunk Operator, it appears the default HEC port `8088` is not exposed by the Splunk containers. 

Currently, I am working around this by patching the StatefulSet that deployed, which technically, the Operator should likely detect and reconcile or revert. Will open another issue on that if required, as it may be a indicator of some work to be done on reconciliation.

**Comment by mikedickey** [comment]
https://github.com/splunk/splunk-operator/pull/2
