### ISSUE TITLE
pass4symkey error reported in ui

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#10]
pass4SymmKey setting in the clustering or general stanza of server.conf is set to empty or the default value. You must change it to a different value.

**Comment by mikedickey** [comment]
Where do you see this error? The operator currently generates four default secrets:

```splunk:
    password: "%s"
    hec_token: "%s"
    idc:
        secret: "%s"
    shc:
        secret: "%s"
```

The containers should use `shc.secret` to set the value for `pass4SymmKey`. Are you using the splunk/splunk:8.0.0 container image? Does you search head cluster status look OK? There could be a bug in splunk-ansible, possibly with a specific role? cc @nwang92

**Comment by mikedickey** [comment]
I just confirmed that the pass4SymmKey in [general] section is the default value "changeme". This is a bug in splunk-ansible (included in the splunk/splunk container), so I'll create another issue and reference it from here.

**Comment by mikedickey** [comment]
https://github.com/splunk/splunk-ansible/issues/316
