### ISSUE TITLE
Splunk Operator: impossible to install 2.1.1 with clean kubectl.

### ISSUE THREAD

**Issue by iaroslav-nakonechnikov** [splunk/splunk-operator#1008]
### Please select the type of request

Bug

### Tell us more

Hello, 

after invoking next command on clean kubernetes: `kubectl apply -f https://github.com/splunk/splunk-operator/releases/download/2.1.1/splunk-operator-cluster.yaml`
i'm getting: 

```
....
"standalones.enterprise.splunk.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

full log attached:

[splunk-operator.log](https://github.com/splunk/splunk-operator/files/10229548/splunk-operator.log)

**Comment by iaroslav-nakonechnikov** [comment]
2.1.0 - same issue

upgrade from 2.0.0 is not working also.

**Comment by kumarajeet** [comment]
Thanks for raising this issue.

We are working on a documentation update to add the correct flags:
Please add the two flags `--server-side --force-conflicts` with the `apply` command.

The command would be then:

 kubectl apply --server-side --force-conflicts -f https://github.com/splunk/splunk-operator/releases/download/2.1.1/splunk-operator-cluster.yaml

**Comment by iaroslav-nakonechnikov** [comment]
hm... 
but this is not meant to be good way, as it may lead to other issues, which will be skipped.

**Comment by iaroslav-nakonechnikov** [comment]
as a small suggestion, please publish it to OCI registry.

**Comment by gaurav-splunk** [comment]
Thanks @iaroslav-nakonechnikov for the suggestion, but the workaround which @kumarajeet mentioned is the solution we have right now. We will work on improving this in future releases.
In the meantime, let me know if it is ok to close this.

**Comment by iaroslav-nakonechnikov** [comment]
yes, lets close for now.
