### ISSUE TITLE
Splunk Operator: Upgrade Documentation Update Request

### ISSUE THREAD

**Issue by splkbdreyer** [splunk/splunk-operator#1019]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
- Update the upgrade guide https://splunk.github.io/splunk-operator/SplunkOperatorUpgrade.html to explicitly state that when upgrading from 1.1 to 2.1 the indexer cluster statefulset is deleted then recreated.  The code from https://github.com/splunk/splunk-operator/blob/2.1.1/pkg/splunk/enterprise/indexercluster.go#L400-L450 indicates the deletion of the statefulset was a temporary workaround for https://splunk.atlassian.net/browse/CSPL-1880, but customers are not expecting an indexer cluster outage during this upgrade.  The documentation needs to include specifics about what happens during this upgrade and why the statefulset is removed.  Based on the linked jira and other information in the code comments, there is an incompatibility between Splunk 8.x and 9.x due to encrypted bundles from the cluster manager that 8.x indexers cannot read.  If that is accurate, then the documentation needs a note about these versions and how/why the upgrade has to perform the steps it does.  This request stems from case 3133020.

**Expected behavior**
- N/A

**Splunk setup on K8S**
- N/A

**Reproduction/Testing steps**
- upgrade from 1.0.3/8.2.2 to 1.1.0/8.2.6 then upgrade to 2.1.0/9.0.2

**K8s environment**
- N/A

**Proposed changes(optional)**
- Add more information to docs.

**K8s collector data(optional)**
- N/A

**Additional context(optional)**
- N/A

**Comment by akondur** [comment]
Hi @splkbdreyer , could you please try with the 2.2.0 release and let us know if the issue is resolved?

**Comment by splkbdreyer** [comment]
@akondur this request was mainly for documentation and it appears the 2.2 documentation has the information requested by the customer so I think this is resolved.

**Comment by akondur** [comment]
Thanks for the quick response @splkbdreyer , closing per the [comment](https://github.com/splunk/splunk-operator/issues/1019#issuecomment-1409042572) above.
