### ISSUE TITLE
Smartstore: Is Azure blob storage supported by Splunk operator ?

### ISSUE THREAD

**Issue by saikalyan551** [splunk/splunk-operator#1065]
### Please select the type of request

Feature Request

### Tell us more

**Describe the request**
In the Smart resource guide, (https://github.com/splunk/splunk-operator/blob/main/docs/SmartStore.md) there is no mention of Azure Blob storage support, Is that supported ? and I am looking to configure Splunk Enterprise on a AKS cluster using the Splunk operator, and I would like to use Smartstore as a storage option, but I cannot find any documentation on how to do so.  Could you please let me know whether it is supported or not? It would be greatly appreciated if you could provide any documentation regarding it.

**Comment by akondur** [comment]
Hi @saikalyan551 , Azure blob is not supported for SmartStore with the operator. Quoting the [SmartStore resource guide](https://github.com/splunk/splunk-operator/blob/main/docs/SmartStore.md#smartstore-resource-guide):

```
SmartStore support in the Splunk Operator is limited to Amazon S3 & S3-API-compliant object stores only if you are using the CRD configuration for S3 as described below."
```

Starting with operator version `1.0.2` using [appFramework](https://github.com/splunk/splunk-operator/blob/main/docs/AppFramework.md) is recommended. Quoting [SmartStore resource guide](https://github.com/splunk/splunk-operator/blob/main/docs/SmartStore.md#smartstore-resource-guide):

```
NOTE: The below method is a temporary way of installing SmartStore configuration & indexes. Starting from the Splunk Operator release 1.0.2, an enhanced App installation framework is introduced which is the recommended method to install SmartStore indexes & configuration.
```

Please let us know what version of the operator is being used with your deployments.

**Comment by saikalyan551** [comment]
Thanks for the quick response @akondur. We are trying to deploy Splunk-operator 2.2.0 using Helm chart in our AKS clusters.

> Azure blob is not supported for SmartStore with the operator.

Is there any timeline for Azure Blob support in the operator ?

**Comment by saikalyan551** [comment]
ohh Thanks!, I'll try it.

**Comment by akondur** [comment]
Hey @saikalyan551 , updated the [comment](https://github.com/splunk/splunk-operator/issues/1065#issuecomment-1428538691) above clarifying SmartStore configuration via the operator.
