### ISSUE TITLE
Using external license master fails after change of precedence in SPLUNK_DEFAULTS_URL

### ISSUE THREAD

**Issue by romain-bellanger** [splunk/splunk-operator#107]
Hello,

In the develop branch, the feature of [using an external license master](https://github.com/splunk/splunk-operator/blob/develop/docs/Examples.md#using-an-external-license-master) is impacted by a [change of precedence of ansible configuration in variable SPLUNK_DEFAULTS_URL](https://github.com/splunk/splunk-operator/pull/101/commits/b4badff7547343184edafb7005d03e2f09a855a8#diff-21314a1ade716f9cd08c98fa46034484R547), from PR #101.

We are following the provided example to define the general pass4SymmKey:
```
splunk:
  license_master_url: license-master.splunk.mydomain.com
  pass4SymmKey: P@ssw0rd
```

However, the pass4SymmKey generated randomly by the operator now takes precedence on the one which we provide as ```/mnt/splunk-secrets/default.yml``` is now placed at the end of environment variable ```SPLUNK_DEFAULTS_URL```. When ansible runs and configures the license master connection on pods, it fails as the pass4SymmKey is incorrect and pods don't start.

**Comment by romain-bellanger** [comment]
Thanks for your reply @akondur. I understand that using the develop branch is at our own risk and breaking changes should be expected. However I see that you have done some additional commits, but the documentation to use an external license master has not been updated. It would be very helpful to have the documentation updated together with that kind of change.

In the solution which you describe ("after my next commit"), could you please explain how the secret containing the pass4SymmKey is mounted to the servers? (as I understand defaultsUrl still can't be used for this because of the generated config having higher precedence)

**Comment by romain-bellanger** [comment]
Hello @akondur. I can see that documentation was added last Friday with #146, so I was finally able to define the pass4symmkey to connect to our license master and use the develop branch (I need the multisite cluster feature which is only in develop, and would like to avoid having to migrate later some new clusters which I have to deploy now). However, I wanted to bring to your attention that [the documentation explaining how to connect to an external license master](https://github.com/splunk/splunk-operator/blob/develop/docs/Examples.md#using-an-external-license-master) has not been updated.

**Comment by akondur** [comment]
Hi @romain-bellanger . I hope you are doing well. Thank you for testing out the external License Master implementation and the subsequent reply here. I have raised a [PR](https://github.com/splunk/splunk-operator/pull/151) for the same and I would appreciate a test/review of the same when you find some time(will be pushing this change very soon).

**Comment by akondur** [comment]
Closing the github issue as the external LM implementation works and documentation has been updated.
