### ISSUE TITLE
Indexer pods restart after stopping splunk service during migration to SmartStore

### ISSUE THREAD

**Issue by adamrushuk** [splunk/splunk-operator#1076]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
- I'm following this guide to "Migrate existing data on an indexer cluster to SmartStore": https://docs.splunk.com/Documentation/Splunk/9.0.3/Indexer/MigratetoSmartStore#2._Run_the_migration_on_the_indexer_cluster
- Cluster Manager can enter maintainance mode without issue
- As soon as I run `$SPLUNK_HOME/bin/splunk stop` on an Indexer pod, it is restarted shortly after due to probe events (`Container splunk failed liveness probe, will be restarted`).
- How can I stop the Indexer pod restarting whilst I follow the migration steps for SmartStore?

**Expected behavior**
- The Indexer pods do not restart after running `$SPLUNK_HOME/bin/splunk stop`

**Splunk setup on K8S**
- Running splunk operator `v2.2.0` using a `c1` configuration with 3 standalone pods:
- 1 x Search head
- 1 x Heavy Forwarder
- 1 x Deployment

**Reproduction/Testing steps**
- Follow the SmartStore migration steps: https://docs.splunk.com/Documentation/Splunk/9.0.3/Indexer/MigratetoSmartStore#2._Run_the_migration_on_the_indexer_cluster
- run `$SPLUNK_HOME/bin/splunk stop` on an Indexer pod

**K8s environment**
- AKS cluster

**Comment by markusspitzli** [comment]
hi @adamrushuk 
We had a similar issue but with SHC members because they took too long for starting up. We set the env variable `NO_HEALTHCHECK` which disabled the healthcheck. The pods aren't killed/restarted anymore. Be aware, it's just a temporary solution for migrating the Smartstore.

**Comment by adamrushuk** [comment]
Thanks @markusspitzli I'll give that a go 👍🏼

**Comment by adamrushuk** [comment]
Using the `NO_HEALTHCHECK` env var stopped the indexers from restarting after I stopped the splunk service on each indexer, so I'll close this now. Thanks again.
