### ISSUE TITLE
Splunk Operator: serviceTemplate.metadata is not working

### ISSUE THREAD

**Issue by adamrushuk** [splunk/splunk-operator#1091]
### Please select the type of request

Bug

### Tell us more

**Describe the request**

Although I can see [spec.serviceTemplate.metadata](https://github.com/splunk/splunk-operator/blob/2.2.0/helm-chart/splunk-operator/crds/enterprise.splunk.com_standalones.yaml#L1521) defined in the CRD, when I define `spec.serviceTemplate.metadata` in a standalone configuration, it doesn't apply to the Standalone configuration.

I can successfully define a `LoadBalancer` serviceTemplate, but without the metadata working, I cannot define `annotations` which severly limits configuration, as annotations are required for an [Internal LoadBalancer in Azure](https://learn.microsoft.com/en-us/azure/aks/internal-lb#create-an-internal-load-balancer).

**Expected behavior**
- When you define `spec.serviceTemplate.metadata` in any CRD, it then reflects in the CRD object within k8s - which I assume would then correctly add `annotations` for the Service in k8s.

**Splunk setup on K8S**
- Running splunk operator `v2.2.0` with a single standalone configuration for testing

**Reproduction/Testing steps**

1. Apply the following configuration:

```bash
cat <<EOF | kubectl apply --namespace splunk-test -f -
apiVersion: enterprise.splunk.com/v4
kind: Standalone
metadata:
  name: standalone
  labels:
    app: SplunkStandAlone
    type: Splunk
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  serviceTemplate:
    metadata:
      labels:
        test: testvalue
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    spec:
      type: LoadBalancer
EOF
```

2. Show the Standalone yaml to see no metadata under serviceTemplate:

```bash
kubectl get Standalone standalone --namespace splunk-test -oyaml | grep serviceTemplate -A3
```

**K8s environment**
- AKS on `v1.23.12`

**Comment by PrymalInstynct** [comment]
Thanks for reporting this, I am experiencing the same behavior.

**Comment by vivekr-splunk** [comment]
@PrymalInstynct  thanks for reporting this issue. we are looking at serviceTemplate issue. will get back to you soon on our investigation.

**Comment by adamrushuk** [comment]
Thanks @vivekr-splunk, looking forward to hearing what you find.

**Comment by vivekr-splunk** [comment]
k8s api server will not consider anything passed in `objectMeta` in serviceTemplate when it creates an entry in `etcd` database for the first time. so the spec when controller gets it will not have anything related to `metadata`. If you want to pass `labels` and `annotations`, pass them in custom resource `annotations` and `labels` , they will be passed to all the resources created by the operator including `service` for example 

```
cat <<EOF | kubectl apply --namespace splunk-test -f -
apiVersion: enterprise.splunk.com/v4
kind: Standalone
metadata:
  name: standalone
  labels:
    app: SplunkStandAlone
    type: Splunk
     test: testvalue
  annotations:
     service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  serviceTemplate:
    spec:
      type: LoadBalancer
EOF
```

here is the service with the annotations 
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  creationTimestamp: "2023-02-27T21:04:05Z"
  labels:
    app.kubernetes.io/component: standalone
    app.kubernetes.io/instance: splunk-test-standalone
    app.kubernetes.io/managed-by: splunk-operator
    app.kubernetes.io/name: standalone
    app.kubernetes.io/part-of: splunk-test-standalone
    test: testvalue
  name: splunk-test-standalone-headless
  namespace: test
  ownerReferences:
  - apiVersion: enterprise.splunk.com/v4
    controller: true
    kind: Standalone
    name: test
    uid: 321fd0d8-84f3-4d92-abfe-3f546e639fac
  resourceVersion: "32052397"
  uid: ea37a007-1308-4721-9a49-febbf449db5b
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-splunkweb
```

**Comment by adamrushuk** [comment]
Thanks for the quick reply @vivekr-splunk.

I've confirmed this works for a `Standalone`, correctly passing on the annotation to the underlying LoadBalancer serviceTemplate, but unfortunately this doesnt work for an `IndexerCluster`; the LoadBalancer is created but has an external IP.

Is there anything else I can try for the `IndexerCluster` config?

**Comment by vivekr-splunk** [comment]
Hello @adamrushuk , I am not sure which service you are looking at. if its headless its set default to clusterIP. I just tested and I can see that serviceTemplate is used in indexer cluster if you see the service (not the headless) for indexer you can find the values set. 

here is the example

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: enterprise.splunk.com/v4
kind: IndexerCluster
metadata:
  annotations:
    annotation: "true"
    meta.helm.sh/release-name: splunk-c3
    meta.helm.sh/release-namespace: test
  creationTimestamp: "2023-02-28T18:59:46Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    label: "true"
  name: idxc
  namespace: test
  resourceVersion: "32334096"
  uid: d9abac4a-cf20-4419-858c-baa2a40ebbf2
spec:
  clusterManagerRef:
    name: cm
  etcVolumeStorageConfig:
    ephemeralStorage: false
    storageCapacity: 10Gi
  livenessInitialDelaySeconds: 300
  readinessInitialDelaySeconds: 10
  replicas: 1
  serviceTemplate:
    spec:
      type: LoadBalancer
  varVolumeStorageConfig:
    ephemeralStorage: false
    storageCapacity: 100Gi
status:
  IdxcPasswordChangedSecrets: {}
  clusterManagerPhase: Ready
```

**Comment by adamrushuk** [comment]
Thanks for testing, @vivekr-splunk.

I can add the `service.beta.kubernetes.io/azure-load-balancer-internal` annotation which correctly shows on the `IndexerCluster`:

```bash
kubectl get idxc idxc --namespace splunk -oyaml
```

```yaml
apiVersion: enterprise.splunk.com/v4
kind: IndexerCluster
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  finalizers:
  - enterprise.splunk.com/delete-pvc
  name: idxc
  namespace: splunk
spec:
  replicas: 3
  serviceTemplate:
    metadata: {}
    spec:
      type: LoadBalancer
```

but although the `IndexerCluster` service does change to a Loadbalancer, the IP address is public (`20.x.x.x`), where it should be a private range:

```bash
kubectl get svc splunk-idxc-indexer-service --namespace splunk -oyaml
```

```yaml
apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: splunk-idxc-indexer-service
  namespace: splunk
  ownerReferences:
  - apiVersion: enterprise.splunk.com/v4
    controller: true
    kind: IndexerCluster
    name: idxc
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.x.x.x
  clusterIPs:
  - 172.x.x.x
  ports:
    [REMOVED]
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 20.x.x.x
```

it appears the `service.beta.kubernetes.io/azure-load-balancer-internal` annotation is not being passed to the `splunk-idxc-indexer-service` loadbalancer service.

Is there anything else I can try?

**Comment by vivekr-splunk** [comment]
that is strange, I just tried the same thing and I can see the annotation 
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  annotations:
    annotation: "true"
    meta.helm.sh/release-name: splunk-c3
    meta.helm.sh/release-namespace: test
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  creationTimestamp: "2023-02-28T19:59:52Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/component: indexer
    app.kubernetes.io/instance: splunk-idxc-indexer
    app.kubernetes.io/managed-by: splunk-operator
    app.kubernetes.io/name: indexer
    app.kubernetes.io/part-of: splunk-cm-indexer
    label: "true"
  name: splunk-idxc-indexer-service
  namespace: test
  ownerReferences:
  - apiVersion: enterprise.splunk.com/v4
    controller: true
    kind: IndexerCluster
    name: idxc
    uid: 6d47ff0d-0e84-4a42-b71d-2743f0f292a4
  resourceVersion: "32347935"
  uid: 770ee93d-dac0-4e05-a453-83290882c964
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.50.24
  clusterIPs:
  - 10.100.50.24
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-splunkweb
    nodePort: 30962
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: http-hec
    nodePort: 30293
    port: 8088
    protocol: TCP
    targetPort: 8088
  - name: https-splunkd
    nodePort: 32362
    port: 8089
    protocol: TCP
    targetPort: 8089
  - name: tcp-s2s
    nodePort: 30391
  selector:
    app.kubernetes.io/component: indexer
    app.kubernetes.io/instance: splunk-idxc-indexer
    app.kubernetes.io/managed-by: splunk-operator
    app.kubernetes.io/name: indexer
    app.kubernetes.io/part-of: splunk-cm-indexer
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: xxxxxx-xxxx.us-west-2.elb.amazonaws.co
```

**Comment by adamrushuk** [comment]
Thanks @vivekr-splunk, I tested again in a new namespace and both the standalone and idxc services have internal IPs now.

**Comment by vivekr-splunk** [comment]
@adamrushuk thats good to know. let me know if I can close this ticket.

**Comment by adamrushuk** [comment]
I've tested this several times on new builds and all have been successful, so thanks again and please close this ticket.
