### ISSUE TITLE
Splunk Operator: Configuring Cluster Domain not possible with Helm Chart

### ISSUE THREAD

**Issue by mag-mkorn** [splunk/splunk-operator#1124]
### Please select the type of request

Enhancement

### Tell us more

**Describe the request**
Add support for configuring a custom cluster domain with the helm chart.

The Domain can be configured for the manifests installation as described [here.](https://splunk.github.io/splunk-operator/Install.html#cluster-domain)

Setting the same configuration item is not supported for the helm chart. Looking at the chart templates there is no other variable that can be utilized to inject the env var into the chart.

**Expected behavior**
Variable in the values file for adding cluster domain or generic env var settings.

**Comment by kabeladev** [comment]
Is there an update on this? As we are facing a similar issue and we would prefer to avoid setting custom env variables.

**Comment by michal-tatusko-splunk** [comment]
Hello @mag-mkorn and @kabeladev 👋
How are you?

Thank you for sharing your feedback. We appreciate your patience. I am happy to share that this issue will be fixed in the upcoming 2.7.0 SOK release, which we plan for December.
