### ISSUE TITLE
Splunk Operator: install specific version via helm

### ISSUE THREAD

**Issue by mpichlba** [splunk/splunk-operator#1186]
### Please select the type of request

Feature Request

### Tell us more

**Describe the request**
- I want to install a specific version of splunk-operator via helm

**Expected behavior**
- helm shows all available versions for install

**Splunk setup on K8S**
- helm chart shows only latest release

**Reproduction/Testing steps**
   > helm repo add splunk https://splunk.github.io/splunk-operator/
   > helm search repo -l splunk
   NAME                            CHART VERSION   APP VERSION     DESCRIPTION
   splunk/splunk-enterprise        2.3.0           2.3.0           A Helm chart for Splunk Enterprise managed by t...
   splunk/splunk-operator          2.3.0           2.3.0           A Helm chart for the Splunk Operator for Kubern...

**K8s environment**
RKE v1.24

**Proposed changes(optional)**
- install other version than the latest one via helm

**Comment by Zeroxcharisma** [comment]
i am facing the same issue tho , any one got a solution ?

**Comment by vivekr-splunk** [comment]
we are working on this issue and PR https://github.com/splunk/splunk-operator/pull/1190 should address this. thank you

**Comment by vivekr-splunk** [comment]
Fixed in 2.3.0 and helm repo list all the versions of splunk operator instances.

**Comment by vivekr-splunk** [comment]
please test and let me know if we can close this ticket

**Comment by Zeroxcharisma** [comment]
i'll update you as soon as possible , and thank you so much

**Comment by vivekr-splunk** [comment]
this is fixed in 2.5.0
