### ISSUE TITLE
Volume should be configured by default

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#12]
a volume should be configured and utilized for all OOB indexes by default. The current default initially creates indexes in Splunk_home an alternate path should be utilized with documentation on annotation of this path with a local or EBS storage path. In the current default approach indexer crash due to out of disk space is likely

**Comment by mikedickey** [comment]
The current approach uses persistent volumes to store all data from $SPLUNK_HOME/etc and $SPLUNK_HOME/var. The persistent volumes are being transparently managed by the operator.
