### ISSUE TITLE
Splunk Operator: Indexer Cluster Search Head with local Indexing

### ISSUE THREAD

**Issue by mag-mkorn** [splunk/splunk-operator#1208]
### Please select the type of request

Enhancement

### Tell us more

**Describe the request**
I would like to configure a Standalone resource as a Search Head that searches an indexer cluster but does not forward any data to the cluster.

This would allow us to spin up test Search Heads in our CI/CD Pipeline for PRs and verify that the apps are working as intended. Local indexing makes sure that created alerts, internal logs etc. don't mess with the production data.

**Proposed changes(optional)**
Add an option that works like `clusterManagerRef`, but only configures the `server.conf` without adding the forwarding configuration to `outputs.conf`.

**Comment by mag-mkorn** [comment]
This would probably add the possibility to search multiple Indexer Clusters as well.

**Comment by vivekr-splunk** [comment]
@mag-mkorn can you try creating an app, that configures standalone to connect to cluster manager.

**Comment by mag-mkorn** [comment]
> @mag-mkorn can you try creating an app, that configures standalone to connect to cluster manager.

That's our workaround, but having the option available in the operator would be way more flexible.

**Comment by michal-tatusko-splunk** [comment]
Hello @mag-mkorn 👋
How are you?

Thank you for raising this enhancement idea. We discussed it within the team and decided to recommend the solution suggested by Vivek above as the way to go moving forward. Unfortunately, we are not planning to add the proposed additional configuration option.
