### ISSUE TITLE
Splunk Operator > Helm Chart: Malformed Deployment artifact

### ISSUE THREAD

**Issue by mvleandro** [splunk/splunk-operator#1225]
When we specify a storageClassName for the PersistentVolumeClaim the helm chart template is creating an invalid Deployment.

I'm fixing it on this PR: https://github.com/splunk/splunk-operator/pull/1223

**Comment by vivekr-splunk** [comment]
cspl-2505

**Comment by vivekr-splunk** [comment]
fixed in 2.5.0
