### ISSUE TITLE
Splunk Operator: Instance migration

### ISSUE THREAD

**Issue by rezonick** [splunk/splunk-operator#1237]
### Please select the type of request

Feature Request

### Tell us more

**Describe the request**
- Deployed a standalone Splunk instance on AWS EKS.
- I want to migrate our standalone Splunk instance to another Availability Zone.
- I'm trying to avoid downtime, I'm not a Splunk expert:
   - I thought to try copying the `/opt/splunk/etc` directly from the old instance to the new one and restarting the server. 
   - I deployed another standalone Splunk instance and tried to migrate the data located in `/opt/splunk/etc` from the old standalone to the new one.
- Initially, I tried to install `aws_cli` and migrate the files via AWS S3 bucket, but it looks like the `splunk` user is very restricted and I wasn't able to install anything.
- I was able to migrate the files via `kubectl cp`, but I failed to extract them to `opt/splunk/etc` probably due to lack of permissions as I received `Operation not permitted`.
- Few questions:
  - Is there any way to deploy the standalone instance with a less restricted user to install the `aws_cli`, or run some system-level commands?
  - If not, can you recommend some other way to achieve my goal of redeploying the instance in another AZ while maintaining its configuration and avoiding downtime?

**Expected behavior**
- Redeploying the Splunk instance in another AZ while maintaining its configuration.

**Splunk setup on K8S**
- Standalone Splunk instance deployed using Splunk Operator.
- Used images:
  - `repository: "docker.io/splunk/splunk-operator:2.3.0"`
  - `repository: "docker.io/splunk/splunk:9.0.3-openjdk11"`

**Reproduction/Testing steps**
-  Default deployment using the supplied images.

**K8s environment**
- AWS EKS 1.27.

Thanks :)

**Comment by yaroslav-nakonechnikov** [comment]
if you are using ebs -> easiest way would be do ebs snapshot and restore it. in another az.

but i believe with standalone version it is not possible to do without downtime.

**Comment by rezonick** [comment]
Thank you @yaroslav-nakonechnikov - it worked 👍🏼 .
