### ISSUE TITLE
Splunk Enterprise Helm Chart - the indexercluster template has a typo

### ISSUE THREAD

**Issue by sweet-mentat** [splunk/splunk-operator#1254]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
- In [helm-chart/splunk-enterprise/templates/enterprise_v4_indexercluster.yaml](https://github.com/splunk/splunk-operator/blob/main/helm-chart/splunk-enterprise/templates/enterprise_v4_indexercluster.yaml), on line 146,
  topologySpreadConstraints:
  needs to be indented two more spaces so that it is aligned with tolerations: on line 141
- When used, I get a helm error because the topologySpreadConstraints key is not valid when the template is parsed.
- The problem is fixed when line 146 is indented two more spaces.

**Expected behavior**
- A valid helm chart.

**Comment by vivekr-splunk** [comment]
cspl-2505

**Comment by vivekr-splunk** [comment]
fixed in 2.5.0
