### ISSUE TITLE
Trigger app deployment on CRD update

### ISSUE THREAD

**Issue by romain-bellanger** [splunk/splunk-operator#126]
Hello,

* This ticket is partially related to issue [Operator deployment of apps](https://github.com/splunk/splunk-operator/issues/43)
* I also opened a ticket to [address some limitations of the app installation solution in splunk-ansible](https://github.com/splunk/splunk-ansible/issues/545)

The main issue which we experience at operator level with the deployment of Splunk apps is that the deployment, either on indexer cluster or search-head cluster, is not triggered automatically when applying a new version of the CRD blueprint. It requires to delete some Kubernetes resources, which complexify the integration to a CD pipeline (and is not supported at all in our CD pipeline). There are two situations:

**1. Configuring the apps through the ```defaults``` property of the CRD:**

The operator creates a ConfigMap with the content of the default properties and mount it to the pods. To trigger a new deployment, ansible needs to be triggered on the cluster-master or the deployer, which can currently be done by deleting the pods.

**2. Provide the URL of a config file in the ```defaultsUrl``` property:**

**This is our preferred method**, because this simplifies the CRD templates, and we can release a versioned ansible config file to our artifact repository within the apps build/CI pipeline together with the apps.
When using this method, the ```defaultsUrl``` property of the CRD is mapped to the environment variable ```SPLUNK_DEFAULTS_URL``` of the managed StatefulSets. The problems are that:
* The StatefulSets are not updated when modifying the ```defaultsUrl``` property of the CRD
* On SearchHeadClusters CRDs, the ```defaultsUrl``` property of the CRD is shared by the StatefulSets managing the deployer and the search-heads. If the StatefulSets were updated, this would trigger a rolling rebuild of the search-head pods, while the deployer would trigger an apply shcluster-bundle, potentially also triggering a rolling restart of the searchhead cluster in parallel.
**Note:** This problem does not really exist on IndexerCluster CRD as the cluster-master can have a dedicated CRD, so with different ```defaultsUrl``` from the indexers.

A possible solution would be to ensure the update of the ```SPLUNK_DEFAULTS_URL``` variable in StatefulSet, and to have a new property ```defaultsUrlDeployer``` in the SearchHeadClusters CRD to control the variable on the deployer StatefulSet independently from the searchheads StatefulSet, to avoid triggering a rebuild of SearchHead pods (if ```defaultsUrlDeployer``` not defined, the deployer could still use the value from ```defaultsUrl``` for backward compatibility).

Another solution would be to have a dedicated Deployer CRD, just like ClusterMaster. This could have some advantages (control compute resources and storage allocation on Deployer) but might be a bit heavy.

**Comment by romain-bellanger** [comment]
In latest versions of the splunk-operator, the variables are now synchronized on the StatefulSets, so a rolling restart is now triggered when modifying the ```defaultsUrl``` property of the ClusterMaster or SearchHeadCluster CRDs. This solves already the concerns about integration in CD pipelines.

On SearchHeadClusters, as the StatefulSets managing the deployer and the search-heads share this property (environment variable ```SPLUNK_DEFAULTS_URL```), the scenario described in the previous comment with double rolling restart of the search heads happen as expected.

However it is not as serious as previously described, because on restart, the deployer pod (ansible) waits for the search head pods to all have completed their restart before to trigger the shbundle deployment (possibly restarting again the searchhead cluster). So at least the two operations are not triggered in parallel.

The impact is that:
* a shbundle deployment which could have been done without restart or with a searchable rolling restart, actually trigger a complete rebuild of the pods, thus increasing the level of service disruption
* the operation takes much longer that what would be needed if only rebuilding the deployer pod

**Proposed solution**
I would again suggest to define a new property ```defaultsUrlDeployer``` in the SearchHeadCluster CRD to control the variable ```SPLUNK_DEFAULTS_URL``` on the deployer independently from the search-heads. If defaultsUrlDeployer not defined, the deployer could still use the value from defaultsUrl for backward compatibility.

**Comment by romain-bellanger** [comment]
My previous comment was based on an operator version which we built ourselves from the develop branch on October 8. We just attempted to install the beta version and we are now back to the previous situation: the StatefulSet is not synchronized on change of defaultUrl.

If my understanding is correct, the code triggering the synchronization of the StatefulSet on diff of environment variable was:
* Added as part of [PR #120](https://github.com/splunk/splunk-operator/pull/120/files#diff-f051fa8775a356c08c90ac411f88b50e7455ec17e8f3241a810b64eb7f00a747)
* Then removed as part of [PR #145](https://github.com/splunk/splunk-operator/pull/145/files#diff-f051fa8775a356c08c90ac411f88b50e7455ec17e8f3241a810b64eb7f00a747) as not required anymore, but I think not considering this use case

**Comment by akondur** [comment]
Hi @romain-bellanger , in the latest release/develop we recycle the pods on a change in env variables. Can we go ahead and close the issue?

**Comment by akondur** [comment]
Closing this issue as its fixed in the latest releases/develop.
