### ISSUE TITLE
Splunk Operator: I can't change minFreeSpace setting using operator in an IndexerCluster

### ISSUE THREAD

**Issue by mvleandro** [splunk/splunk-operator#1263]
### Please select the type of request

Feature Request

### Tell us more

**Describe the request**
- I couldn't find where to change the value for the setting minFreeSpace using the operator in an IndexerCluster.

**Expected behavior**
- I should have an easy way to change it by adding a property in the Helmchart values for example.

**Splunk setup on K8S**
- I'm using the HelmChart splunk-operator 2.3.1. I'm deploying a multi-site IndexerCluster.

**Proposed changes(optional)**
- I should have an easy way to change it by adding a property in the Helmchart values for example.

**Comment by vivekr-splunk** [comment]
have you used `default.yml` . please check https://github.com/splunk/splunk-operator/blob/main/docs/Examples.md for example.

**Comment by akondur** [comment]
Closing this issue. @mvleandro Please re-open the issue if the suggested workaround does not work.
