### ISSUE TITLE
Splunk Operator: No way to start searchheads independently from CM

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [splunk/splunk-operator#1267]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
There is a need to start cluster of searcheads wihtout pointing to any cluster manager and indexers.
and as it was suggested in https://github.com/splunk/splunk-operator/discussions/1227 , i'm creating that issue.

**Expected behavior**
Removing cluster manager ref will be ignored and searchhead cluster will be started without any issues.

**Splunk setup on K8S**
 - aws eks

**Reproduction/Testing steps**
- just remove cluster manager ref from config and it will fail

**Comment by logsecvuln** [comment]
could someone please take a look into this @vivekr-splunk  @jryb @kumarajeet

**Comment by vivekr-splunk** [comment]
@yaroslav-nakonechnikov we will look at this issue and get back to you

**Comment by akondur** [comment]
Hey @yaroslav-nakonechnikov , can you try this with the new Splunk operator version 2.5.1?

**Comment by yaroslav-nakonechnikov** [comment]
@akondur so, am i understand correct, that to start searchhead independently, it should be possible just remove clusterManagerRef?

or something else is needed?

**Comment by akondur** [comment]
Hey @yaroslav-nakonechnikov , can you give us some more details here so we can make progress on this issue?

**Comment by yaroslav-nakonechnikov** [comment]
@akondur  i can't do check without solving https://github.com/splunk/splunk-operator/issues/1293
as 2.5.x is causing issues, which we can't debug.

**Comment by vivekr-splunk** [comment]
@yaroslav-nakonechnikov can you recheck this issue and let us know if this is working for you now.

**Comment by yaroslav-nakonechnikov** [comment]
thanks for pinging, i'll recheck and will update it.

**Comment by yaroslav-nakonechnikov** [comment]
yes, looks like it works now, thanks!
