### ISSUE TITLE
+1 to use of config file (defaults.yml) for setting up config

### ISSUE THREAD

**Issue by aegershman** [splunk/splunk-operator#13]
This isn't an issue, and it might make more sense in the `splunk-ansible` repo, but just wanted to share this-- so far I've had a positive experience swapping out the use of manually mounting configMaps and such with the `defaults.yml` that's passed in to configure Splunk.

Over a year ago my team and I wrote a little rinky-dink stateless Splunk HEC chart, [and recently I've been doing some work to expand (it until the time is right to move to something more official)](https://github.com/aegershman/splunk-helm-chart/pull/54)).

Just wanted to say that the decision to have a limited set of configuration options defined in config `yml` has made things a lot easier, and I'm sure will make it easier to move config again in the future.

Just wanted to say that and say thanks to you all OSS maintainers & contributors do to make this available 👍

**Comment by mikedickey** [comment]
I believe this is already covered by the `defaults` and `defaultsUrl` parameters. Imagine that is why you closed it, but just wanted to add the reference for posterity. From [SplunkEnterprise Parameters](https://splunk.github.io/splunk-operator/SplunkEnterprise.html) docs:

```
defaults | string | Inline map of default.yml overrides used to initialize the environment
defaultsUrl | string | Full path or URL for one or more default.yml files, separated by commas
```

**Comment by aegershman** [comment]
Right, I was just saying I liked the design, I wasn't trying to report anything as a problem. Apologies for confusion. Github doesn't really have a way to indicate "I like this / have had good experiences with the design" outside the context of an 'issue' 👌

**Comment by mikedickey** [comment]
Got it, thank you! :)
