### ISSUE TITLE
Splunk Operator: Splunk 9.2.1 issues

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [splunk/splunk-operator#1313]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
```
TASK [splunk_common : Check Splunk instance is running] ************************
fatal: [localhost]: FAILED! => {}

MSG:

The conditional check 'task_response.status == 200' failed. The error was: error while evaluating conditional (task_response.status == 200): 'dict object' has no attribute 'status'
...ignoring
Tuesday 02 April 2024  13:53:34 +0000 (0:00:01.548)       0:03:01.116 *********
```

**Expected behavior**
it works good.

**Comment by yaroslav-nakonechnikov** [comment]
There is already several patches for 9.2 but `splunk-operator` still doesn't support it. 

meanwhile, in 9.2 there are quite big changes and i would say, that is is already expected to see it working.

**Comment by yaroslav-nakonechnikov** [comment]
with 9.2.1-patch2 looks better

**Comment by akondur** [comment]
Hi @yaroslav-nakonechnikov , are you still continuing to see any instances of the error log with 9.2.1-patch2?

**Comment by yaroslav-nakonechnikov** [comment]
@akondur  we are going to upgrade on prod to 9.2.1 today, so then i'll tell more.

**Comment by yaroslav-nakonechnikov** [comment]
yes, upgrade completed. all looks working
