### ISSUE TITLE
Ability to configure props.conf

### ISSUE THREAD

**Issue by nziebart** [splunk/splunk-operator#1324]
Currently there does not seem to be any support for configuring props.conf via the operator. This is a fairly basic and essential feature; it would be great to add support for this or else add guidance to the [readme](https://github.com/splunk/splunk-operator/blob/main/docs/README.md) if it already exists.

**Comment by akondur** [comment]
Hey @nziebart , did you get a chance to look at the appFramework [feature](https://github.com/splunk/splunk-operator/blob/main/docs/AppFramework.md) to configure props.conf? Is there anything specific about this configuration which cannot be captured in an app?

**Comment by yaroslav-nakonechnikov** [comment]
there are 2 ways at least:
1 - via defaults.yml
2 - via custom splunk _app_

we are using 2nd way.

**Comment by vivekr-splunk** [comment]
Please use the app configuration as mentioned by @yaroslav-nakonechnikov for props.conf.  Here is the documentation https://github.com/splunk/splunk-operator/blob/main/docs/AppFramework.md

**Comment by vivekr-splunk** [comment]
Can we close ticket since we have solution with app management

**Comment by akondur** [comment]
Hi @nziebart , please let us know if we can close out this issue.

**Comment by michal-tatusko-splunk** [comment]
Hello @nziebart,
We will close the issue. Please feel free to reopen if it still exists.
