### ISSUE TITLE
App Framework: First Class Support for GCP

### ISSUE THREAD

**Issue by leetreveil** [splunk/splunk-operator#1334]
### Please select the type of request

Enhancement

### Tell us more

**Describe the request**
- GCP should be a first class citizen in AppFramework.

Currently, an administrator running Splunk with the operator on GCP needs to use the minio provider to talk to GCS.

This is deficient for a couple of reasons:

1. Minio requires AWS style HMAC access keys to be provisioned and stored as a k8s secret.
1.1. In secure environments on GCP, [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) +  [ Application Default Credentials](https://cloud.google.com/docs/authentication/provide-credentials-adc) is preferred. 
3. Documentation around GCP support is poor and setup instructions are not clear.

**Expected behavior**
-  GCP should become a first class citizen in AppFramework with tight integration into Workload Identity + ADC.

**Comment by vivekr-splunk** [comment]
@leetreveil thank you for raising request, we have plan for adding GCP support through sdk, we will update when that is done.

**Comment by vivekr-splunk** [comment]
Hello @leetreveil we are working on supporting this feature. currently we are working towards spike to test the feature changes. will update you when we are ready with the changes.

**Comment by akondur** [comment]
Closing this issue as appframework supports GCP natively on 2.7.0 release.
