### ISSUE TITLE
Splunk Operator: build is not hermetic

### ISSUE THREAD

**Issue by paheath** [splunk/splunk-operator#1345]
### Please select the type of request

Bug

### Tell us more

The image is built on [ubi8:latest](https://github.com/splunk/splunk-operator/blob/dafc9d3dbbd45fff7322daa13550af35527ef921/Dockerfile#L25), meaning a build from the same commit could use a different base image depending on what `latest` points to at any given time. It would be preferable to point to a more specific tag or sha so old builds are repeatable.

**Comment by akondur** [comment]
Hey @paheath , can you check if this [MR](https://github.com/splunk/splunk-operator/pull/1349) fixes the issue?

**Comment by paheath** [comment]
I would use the digest instead of a tag. I think docker-splunk needs the same change. https://github.com/splunk/docker-splunk/blob/9b55b6960ee00f54c19a25a86a178f998824711b/base/redhat-8/Dockerfile#L19

**Comment by akondur** [comment]
Hey @paheath , can you open a separate issue on the docker-splunk repo here? Meanwhile, we are evaluating the fix on the Splunk Operator side.

**Comment by paheath** [comment]
Done https://github.com/splunk/docker-splunk/issues/682

**Comment by michal-tatusko-splunk** [comment]
Thank you for raising this bug. We will look into that shortly.

**Comment by rlieberman-splunk** [comment]
This will be fixed in release 2.7.

**Comment by akondur** [comment]
Closing this issue as it is fixed in the release.
