### ISSUE TITLE
Splunk Operator: verify RF peer failed could not get cluster info from cluster manager

### ISSUE THREAD

**Issue by jadamkhhh** [splunk/splunk-operator#1347]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
- Indexer and search head not creating. I can see the kubectl events below. Search heads are not schedule by the cluster at all.
`LAST SEEN               TYPE      REASON          OBJECT                          MESSAGE
6m50s                   Warning   verifyRFPeers   IndexerCluster/splunk-indexer   verify RF peer failed could not get cluster info from cluster manager`

**Expected behavior**
- Indexer and search head instances start successfully.

**Comment by michal-tatusko-splunk** [comment]
Hello @jadamkhhh 
Thank you for raising this bug. 
It looks like the Cluster Manager is not coming up. Could you please check and provide us with logs?

**Comment by akondur** [comment]
Hey @jadamkhhh , could you please check and provide us the logs?

**Comment by akondur** [comment]
Hey @jadamkhhh , closing the issue for now. Please re-open it with more details if you see the issue re-occurring.
