### ISSUE TITLE
Splunk Operator: Could not get the Cluster Manager Image. 

### ISSUE THREAD

**Issue by TheFausap** [splunk/splunk-operator#1348]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
After an update to a cluster bundle the repo, adding some remote volumes, the cluster manager started a rolling restart as expected, but all the indexers are now down. In the events of the indexer CSV I found this error

Could not get the Cluster Manager Image.  Stateful set spl-cm-cluster-manager not found.

Of course, the stateful set is there up and running, and my cluster manager is up and running.

**Expected behavior**
- After the rolling restart the cluster should be up with all the peers.

**Splunk setup on K8S**
- Splunk is using the operation version 2.5.1 under RedHat Openshift 4.14.29

**Comment by michal-tatusko-splunk** [comment]
Thank you for raising this bug. We will look into that shortly.

**Comment by vivekr-splunk** [comment]
@TheFausap can you provide us more details with regard to this issue. please share the  indexer log files. and Custom resource

**Comment by akondur** [comment]
Hi @TheFausap , could you please provide us with more details?

**Comment by TheFausap** [comment]
Hi @akondur I cannot give you too much information right now, because we uninstalled the operator and after the re-installation, everything was back to normal. At the moment this error is not happening anymore. I don't know if you want to keep this issue open, or we could close it and I will reopen a new one if this error pops up again.

**Comment by michal-tatusko-splunk** [comment]
Hello @TheFausap,
I am glad to hear you are no longer experiencing the issues. I will close it, as there's no way to reproduce this bug. Please feel free to reopen the issue if the behavior occurs again.
