### ISSUE TITLE
Support many-to-many SHC-to-IDXC connections in SHC CRD

### ISSUE THREAD

**Issue by jkoby** [splunk/splunk-operator#163]
Currently the CRDs allow for a single ClusterMaster to be referenced in a SearchHeadCluster or IndexerCluster.  This works for environments that only have one indexer cluster that needs to be searched by a given SearchHeadCluster.

To have a SHC search more than one IndexerCluster, it's currently required to override parts of default.yml.  Would it be possible to have clusterMasterRef for SearchHeadCluster accept a list of ClusterMasters, rather than just one?  

This is separate from the multisite_clustermaster setting in default.yml that was released in v0.2.0

**Comment by gaurav-splunk** [comment]
Probably similar to this https://github.com/splunk/splunk-operator/issues/41 ?

**Comment by jkoby** [comment]
Closing this issue as a duplicate of #41
