### ISSUE TITLE
HTTP Event Collector should be configured with HTTP (not HTTPS)

### ISSUE THREAD

**Issue by outcoldman** [splunk/splunk-operator#170]
Seems like on the Indexers `default.yaml` has an option `hec_enableSSL`

```
kubectl exec -it splunk-cluster-indexer-0 -- bash
[splunk@splunk-cluster-indexer-0 splunk]$ cat /mnt/splunk-secrets/default.yml

splunk:
    hec_disabled: 0
    hec_enableSSL: 0
...
```

But does not seem like it is applied 

```
[splunk@splunk-cluster-indexer-0 splunk]$ cat etc/apps/splunk_httpinput/local/inputs.conf
[http]
disabled = 0

[http://splunk_hec_token]
disabled = 0
token = XXX
```

Obviously for ingress with the SSL enabled, that will not work.

**Comment by pogdin** [comment]
@outcoldman you do or do not want SSL set on HEC?

Setting on globally far as I can tell.

`[splunk@splunk-example-indexer-0 default]$ pwd
/opt/splunk/etc/apps/splunk_httpinput/default
[splunk@splunk-example-indexer-0 default]$ cat inputs.conf
[http]
disabled=1
port=8088
enableSSL=1
dedicatedIoThreads=2
maxThreads = 0
maxSockets = 0
useDeploymentServer=0
# ssl settings are similar to mgmt server
sslVersions=*,-ssl2
allowSslCompression=true
allowSslRenegotiation=true
ackIdleCleanup=true
[splunk@splunk-example-indexer-0 default]$ pwd
/opt/splunk/etc/apps/splunk_httpinput/default
[splunk@splunk-example-indexer-0 default]$ cat inputs.conf
[http]
disabled=1
port=8088
enableSSL=1
dedicatedIoThreads=2
maxThreads = 0
maxSockets = 0
useDeploymentServer=0
# ssl settings are similar to mgmt server
sslVersions=*,-ssl2
allowSslCompression=true
allowSslRenegotiation=true
ackIdleCleanup=true
`

**Comment by outcoldman** [comment]
@pogdin you probably don't want to enable SSL, considering that after that you will run HEC behind the ingress, that will have a SSL termination, see https://github.com/splunk/splunk-operator/blob/master/docs/Ingress.md#example-configuring-ingress-using-nginx

**Comment by pogdin** [comment]
Got it @outcoldman , thanks.  @gaurav-splunk , concur?

**Comment by gaurav-splunk** [comment]
@outcoldman only setting `hec_enableSSL: 0` wouldn't cut the deal for you. You have to also set this to disable SSL for hec - 
```
splunk:
   hec:
     ssl: False
```

**Comment by gaurav-splunk** [comment]
@outcoldman Is it good to close this issue now?
