### ISSUE TITLE
UF Node Agent

### ISSUE THREAD

**Issue by MikeTomlin19** [splunk/splunk-operator#181]
The splunk-k8s fluentd project is not able to scale to the size of our nodes and the log volume of the containers on them. Can we add the UF node agent to this project so that we can use that instead of fluentd for sending container logs to splunk?

**Comment by pogdin** [comment]
Thanks Mike.  We are considering this as a portion of the Operator work but this will most likely be delivered through https://github.com/splunk/splunk-connect-for-kubernetes

**Comment by akondur** [comment]
Hey @MikeTomlin19 , the requested feature will be delivered through the [Splunk Connect for K8s project](https://github.com/splunk/splunk-connect-for-kubernetes).

**Comment by MikeTomlin19** [comment]
Thanks @akondur   I don't see an option in that project to use the Universal Forwarder for logs, instead of Fluentd. Would you mind pointing me to that, please?

**Comment by akondur** [comment]
Hi @MikeTomlin19 , please open an issue on the [Splunk Connect for K8s repo](https://github.com/splunk/splunk-connect-for-kubernetes/issues) to get the information required.
