### ISSUE TITLE
Installing Splunk Apps via Kubernetes Configmap fails with "RequestEntityTooLarge"

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-operator#20]
```
docker-splunk image version: splunk/splunk:8.0.1
Kubernetes variant: MicroK8s
Issue: Hit limit on configmap trying to store 4 Splunk apps. 
Workaround: Burned the apps into the Docker image instead of configmap and will look at running a local repo instead to pull from URI. 
```

Happy New Year all!

Using `splunk/splunk:8.0.1` on MicroK8s and it is working nicely thus far! Stock standalone deploy is working beautifully. 

Figure I'd share something I ran into trying to recently as I tried to install 4 Splunk apps to my standalone Splunk instance via configmap method:

```kubectl -n splunk create configmap splunk-apps --from-file=splunk-app-for-infrastructure_201.tgz --from-file=splunk-add-on-for-infrastructure_201.tgz --from-file=splunk-business-flow_116.tgz --from-file=ta_container_workshop.tgz
Error from server (RequestEntityTooLarge): Request entity too large: limit is 3145728
```
I assume I could mount multiple configmaps, but I am not sure multiple app paths are supported? Assuming it is not?

I have workarounds, for now, but figured I'd capture this experience for science!

**Comment by mikedickey** [comment]
Hi Matt, as a work-around, there shouldn't be any problem using a separate ConfigMap for each app and mounting each as its own `splunkVolume`.

Where do you see that "RequestEntityTooLarge" error? I'm wondering if ConfigMap may have limitations in how large it can/should be. I doubt it was originally intended to be used for BLOBs. Using a Volume that can be mounted read-only by multiple pods may be preferred for storing collections of apps over a certain size.

**Comment by matthewmodestino** [comment]
Yeah it's totally got to be a limit on configMap size, saw it returned from `kubectl`. 

Ah ok! I think I understand, as long as the path the configMap is mounted to is resolvable when i put it in the `apps_location` I should be all good, right?

**Comment by mikedickey** [comment]
Could also be an exception coming from ansible's uri module when request body exceeds a limit?

From [splunk-ansible](https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_common/tasks/install_apps.yml):
```- name: Install app via REST
  uri:
    url: "{{ cert_prefix }}://127.0.0.1:{{ splunk.svc_port }}/services/apps/local"
    method: POST
    user: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    validate_certs: false
    body:
      name: "/tmp/app.spl"
      update: "true"
      filename: "true"
    body_format: "form-urlencoded"
    status_code: [ 200, 201 ]
    timeout: 90
  when:
    - "'splunkbase.splunk.com' not in app_url"
    - "'itsi' not in app_contents.stdout_lines"
  no_log: "{{ hide_password }}"
```

**Comment by mikedickey** [comment]
So the error is coming from `kubectl` when you try to create the ConfigMap? If so, then it must be a limit set either in k8s api server or in `kubectl`.

`apps_location` can use any path; it is an independent feature from `splunkVolume` that just happens to work nicely with it. So, no limitations or expectations..

**Comment by matthewmodestino** [comment]
cool ill try it then close this! thanks!

**Comment by Caldas** [comment]
Hey @mikedickey, as @matthewmodestino said this can be closed 👍
