### ISSUE TITLE
Guidelines for the usage of emptyDir in production for ClusterMaster

### ISSUE THREAD

**Issue by romain-bellanger** [splunk/splunk-operator#226]
According to [the documentation](https://github.com/splunk/splunk-operator/blob/develop/docs/StorageClass.md#ephemeral-storage) the usage of ephemeral storage on Splunk pods is discouraged and not supported in production, and this statement seems to apply indifferently to all Splunk components. However:
1. The Monitoring Console automatically created by the splunk-operator since 0.2.0 writes to the docker container layer which is ephemeral storage (note: #201 might switch to emptyDir) without possibility to configure persistent storage
2. My understanding is that nothing requires persistence on cluster master beyond configuration (which is anyway redeployed by ansible on pod restart). When shutting down a cluster and restarting the master, it doesn't seem to remember anything about indexers which were previously connected to it, until they reconnect.
3. This could actually have some benefits for resiliency:
    1. On some cloud infrastructure providers (e.g. our private Openstack cloud) persistent volumes are bound to an availability zone. In that case, using persistent volumes prevents the cluster master to be automatically rescheduled to a different zone in case of zone or rack complete failure. It is then unable to reassign primary buckets and to keep all the data searchable. Allowing ephemeral storage would make the procedure [Handle manager site failure](https://docs.splunk.com/Documentation/Splunk/8.1.1/Indexer/Managersitefailure) fully automated (no kind of data synchronization seems to be required on the stand-by manager according to the doc).
    2. Splunk app deployment currently doesn't support fallback (removal of an app). If ephemeral storage is used (at least on /opt/splunk/etc) this solves the problem.

Could you please review the possibility to support ephemeral storage in production for the cluster master, and possibly also for the deployer if a dedicated CRD is created for it at some point.

**Comment by pogdin** [comment]
Closing as we don't support emptyDir on the CM.  Will re-evaluate as HA/Multisite Cluster Manager work progress in Splunk platform.
