### ISSUE TITLE
HTTP 401 in splunk-operator logs after password change

### ISSUE THREAD

**Issue by akantak** [splunk/splunk-operator#229]
When I create a cluster master I get errors in the splunk operator logs:

> {"level":"info","ts":1610981094.3596175,"logger":"splunk.reconcile.Reconcile","msg":"Reconciling custom resource","Group":"enterprise.splunk.com","Version":"v1beta1","Kind":"ClusterMaster","Namespace":"default","Name":"example-cm"}
> {"level":"info","ts":1610981094.3803444,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-example-cm-indexer-service","namespace":"default"}
> {"level":"info","ts":1610981094.3853102,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-example-cm-cluster-master-service","namespace":"default"}
> {"level":"info","ts":1610981094.4181035,"logger":"splunk.reconcile.UpdateStatefulSetPods","msg":"All pods are ready","name":"splunk-example-cm-cluster-master","namespace":"default"}
> {"level":"info","ts":1610981094.430803,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-default-monitoring-console-service","namespace":"default"}
> {"level":"info","ts":1610981094.4349644,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-default-monitoring-console-headless","namespace":"default"}
> {"level":"error","ts":1610981094.4657013,"logger":"splunk.reconcile.Reconcile","msg":"Reconciliation requeued","Group":"enterprise.splunk.com","Version":"v1beta1","Kind":"ClusterMaster","Namespace":"default","Name":"example-cm","RequeueAfter":5,"error":"Response code=401 from https://splunk-example-cm-cluster-master-service.default.svc.cluster.local:8089/services/cluster/config?count=0&output_mode=json; want [200]","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgo/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/splunk/splunk-operator/pkg/splunk/controller.splunkReconciler.Reconcile\n\tsplunk-operator/pkg/splunk/controller/controller.go:125\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
> {"level":"info","ts":1610981094.4670367,"logger":"splunk.reconcile.Reconcile","msg":"Reconciling custom resource","Group":"enterprise.splunk.com","Version":"v1beta1","Kind":"ClusterMaster","Namespace":"default","Name":"example-cm"}
> {"level":"info","ts":1610981094.4851515,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-example-cm-indexer-service","namespace":"default"}
> {"level":"info","ts":1610981094.4893692,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-example-cm-cluster-master-service","namespace":"default"}
> {"level":"info","ts":1610981094.5226765,"logger":"splunk.reconcile.UpdateStatefulSetPods","msg":"All pods are ready","name":"splunk-example-cm-cluster-master","namespace":"default"}
> {"level":"info","ts":1610981094.5360448,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-default-monitoring-console-service","namespace":"default"}
> {"level":"info","ts":1610981094.539988,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-default-monitoring-console-headless","namespace":"default"}
> {"level":"error","ts":1610981094.5629578,"logger":"splunk.reconcile.Reconcile","msg":"Reconciliation requeued","Group":"enterprise.splunk.com","Version":"v1beta1","Kind":"ClusterMaster","Namespace":"default","Name":"example-cm","RequeueAfter":5,"error":"Response code=401 from https://splunk-example-cm-cluster-master-service.default.svc.cluster.local:8089/services/cluster/config?count=0&output_mode=json; want [200]","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgo/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/splunk/splunk-operator/pkg/splunk/controller.splunkReconciler.Reconcile\n\tsplunk-operator/pkg/splunk/controller/controller.go:125\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}

### **Reproduction:**
I create the secret (with password `changeme`):
```
apiVersion: v1
data:
  password: Y2hhbmdlbWU=
kind: Secret
metadata:
  name: splunk-default-secret
  namespace: default
type: Opaque
```
I create a standard splunk-operator, version 0.2.1 (I only added namespace `default` to all definitions that support it).
No errors in splunk-operator logs so far.
Now I create the cluster master using the definition:
```
apiVersion: enterprise.splunk.com/v1beta1
kind: ClusterMaster
metadata:
  name: example-cm
  namespace: default
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  etcStorage: "100Gi"
  varStorage: "10Gi"
```
After the pod becomes ready I see the errors mentioned in the first quote.

Kubernetes version (installed using kubespray):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

I get similar errors for search heads and indexers too (when created).

Also, I am not able to remove the clustermaster, CRD shows Phase "Error" and I can do nothing.

**Comment by pogdin** [comment]
Can you try this without creating the secret first?  So, create your Splunk deployment, then change the secret as described here: https://github.com/splunk/splunk-operator/blob/develop/docs/Examples.md#updating-global-kubernetes-secret-object

**Comment by akantak** [comment]
@pogdin the flow that you suggested looks good (CRDs in a ready state, no error in the splunk-operator logs) until the password change. I used there:
```
kubectl patch secret splunk-default-secret -p='{"data":{"password": "Y2hhbmdlbWU="}}' -v=1
```
After secret patching, there were created new secrets with v2 suffix and from the list of instances:
```
splunk-default-monitoring-console-0       1/1     Running   0          37m
splunk-example-cm-cluster-master-0        1/1     Running   0          11m
splunk-example-deployer-0                 1/1     Running   0          11m
splunk-example-indexer-0                  1/1     Running   0          42m
splunk-example-indexer-1                  1/1     Running   0          42m
splunk-example-indexer-2                  1/1     Running   0          42m
splunk-example-search-head-0              1/1     Running   0          43m
splunk-example-search-head-1              1/1     Running   0          43m
splunk-example-search-head-2              1/1     Running   0          43m
```
Only cluster master and deployer got restarted. Nevertheless, cluster master started using splunk-example-cm-cluster-master-secret-v2 and the errors from my first message in splunk-operator appeared.

**Comment by pogdin** [comment]
Can you try using a password other than changeme?  The pods might be purposefully rejecting this as it was the Splunk default for many years before we mandating changing the admin password for security reasons.

**Comment by akantak** [comment]
@pogdin you fixed that :) using any different password works fine, only `changeme` causes the issues
