### ISSUE TITLE
Recommendations regarding the configuration of Transparent Huge Pages (THP)

### ISSUE THREAD

**Issue by romain-bellanger** [splunk/splunk-operator#232]
Splunk [recommends to disable Transparent Huge Pages](https://docs.splunk.com/Documentation/Splunk/8.1.1/ReleaseNotes/SplunkandTHP) to prevent a significant degradation of performances. However doing this on a Kubernetes cluster raises some questions if the cluster is shared with other applications:

* What is the impact of disabling THP on the other applications running on the Kubernetes cluster?
* If important impact on other applications, do we need dedicated k8s nodes for Splunk? (potentially shared with other datastores)
* Then do all the Splunk components need to have THP disabled? (e.g. cluster-master)

This is where we stand on this question:

* On different k8s clusters with dedicated nodes for indexer pods, we disabled THP one of the nodes and didn't observe any difference in term of CPU consumption or system load with the other nodes. We are however worried about possible difficulties with Splunk support if THP is not disabled: this would probably always be the first recommendation before digging into our problems.
* Searching on google about applications getting benefit from THP, we didn't find much information but it seems like this is limited to very specific cases
* Our understanding is that running Splunk pods on shared k8s nodes, especially together with stateless applications, could have some benefits. In general, the VM types offered by the different public cloud providers have limits in terms of bandwith and IOps, limiting the total bandwidth and IOps of all the persistent volumes mounted on them. Spreading Splunk pods over a larger number of VMs shared with stateless applications could allow Splunk to make use of the available bandwidth on all the VMs, while having dedicated nodes (with THP disabled) with only Splunk (or datastore) pods might require to choose expensive VM types optimized for high storage throughput.
* The cluster-master should rather run on different nodes than indexers, so if possible not Splunk dedicated nodes with THP disabled if that's the chosen architecture, so that they don't fail at the same time, which would impact the transfer of primary bucket and the searchability of data.

It would be nice to have some guidance on these choices in the documentation, even just reminding the recommendation to disable THP on Kubernetes nodes if applicable.

**Comment by pogdin** [comment]
#https://github.com/splunk/splunk-operator/commit/c802f8ff78f81e96722d96332b07cb175991974e#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938
