### ISSUE TITLE
Proposal to include SOK in OperatorHub

### ISSUE THREAD

**Issue by dmesser** [splunk/splunk-operator#24]
Hi Splunk team, since you are using the Operator-SDK for the Splunk you are not that far away to generate CSV and publish your Operator at [OperatorHub.io](https://operatorhub.io). The SDK supports creating most of the CSV skeleton for you via the `gen-csv` subcommand or you can use a graphical UI at https://operatorhub.io/bundle drop in your k8s manifest and wrap up the rest of the metadata.

WDYT?

**Comment by mikedickey** [comment]
We are working on this and hope to have it included soon.

**Comment by dmesser** [comment]
Awesome, looking forward to your PR.

**Comment by mikedickey** [comment]
PR for OperatorHub submission is at https://github.com/operator-framework/community-operators/pull/1027

**Comment by mikedickey** [comment]
https://operatorhub.io/operator/splunk
