### ISSUE TITLE
Provide support to use a user other than 41812

### ISSUE THREAD

**Issue by c3-davidtran** [splunk/splunk-operator#242]
Currently, we cannot specify which user ID the pods should use.
It would be a big help to enable this feature for users running on restricted environments like Openshift.

**Comment by pogdin** [comment]
Hi, thanks for submitting your issue.  Can you verify this does not meet your requirements?

https://github.com/splunk/splunk-operator/blob/develop/docs/OpenShift.md

**Comment by c3-davidtran** [comment]
Hello,
Thanks for your reply, using nonroot scc would allow me to run as user 41812, however, I have a case scenario where I'm only allowed to use and run pods using specific unprivileged UIDs (41812 does not belong to the ones I'm allowed to use).

So my requirement would be to provide my own specific UID to the Pods deployed by the operator.

**Comment by akondur** [comment]
Hi @c3-davidtran , as of now the docker-splunk project supports only three users **ansible(999), splunk(41812) or root(0)** as per the security [documentation](https://github.com/splunk/docker-splunk/blob/develop/docs/SECURITY.md). The Splunk Operator hardcodes UID/GID of the container as **41812** as that is the recommended user/group for production. If **root(0) or ansible(999)** need to be configured on containers by the operator for testing purposes a custom image can be built by making a change to the **podSecurityContext** [here](https://github.com/splunk/splunk-operator/blob/7098178a23c4a51f81f20027ecf0be7b0821b0e1/pkg/splunk/enterprise/configuration.go#L704).

Until docker-splunk adds support for dynamic users, the Splunk Operator is unable to pass over any configuration via K8s for a random UID to be set as UID/GID of the container. If such a docker-splunk enhancement is implemented, making the **podSecurityContext** configurable via CR spec will be considered.

Closing the issue as it's out of scope of the operator at the moment.
