### ISSUE TITLE
Monitoring Console pod can't restart after License Change

### ISSUE THREAD

**Issue by lappodeveloper** [splunk/splunk-operator#247]
It seems that after changing the License, the monitoring console pod has some kind of problem after restarting.

_Reproduce (tested on AKS):_

`#> kubectl apply -f https://github.com/splunk/splunk-operator/releases/download/0.2.1/splunk-operator-install.yaml
`

```
#> cat <<EOF | kubectl apply -f -
apiVersion: enterprise.splunk.com/v1beta1
kind: Standalone
metadata:
  name: s1
  finalizers:
  - enterprise.splunk.com/delete-pvc
EOF
```

```
#> kubectl get pods
NAME                                   READY   STATUS    RESTARTS   AGE
splunk-default-monitoring-console-0    1/1     Running   0          2m1s
splunk-operator-5dc7c7c459-nvqbh       1/1     Running   0          5m5s
splunk-s1-standalone-0                 1/1     Running   0          4m32s

```

```
#> kubectl port-forward splunk-s1-standalone-0 8000 
Forwarding from 127.0.0.1:8000 -> 8000
Forwarding from [::1]:8000 -> 8000
Handling connection for 8000

```

===> http://localhost:8000/
===> Settings -> License -> Change License Group -> "Free License" -> Save -> Restart Now -> Ok

(wait some time until 'splunk-s1-standalone-0' restarts...)

```
#> kubectl get pods
splunk-default-monitoring-console-0    1/1     Running   0          7m49s
splunk-operator-5dc7c7c459-nvqbh       1/1     Running   0          10m
splunk-s1-standalone-0                 1/1     Running   1          10m


```
```
#> kubectl delete statefulsets.apps splunk-default-monitoring-console 
statefulset.apps "splunk-default-monitoring-console" deleted

```

```
#> kubectl get pods
splunk-default-monitoring-console-0    0/1     Running   0          111s
splunk-operator-5dc7c7c459-nvqbh       1/1     Running   0          14m
splunk-s1-standalone-0                 1/1     Running   1          14m


```
```
#> kubectl logs -f splunk-default-monitoring-console-0
....
Monday 08 February 2021  14:08:34 +0000 (0:00:00.035)       0:00:48.505 ******* 
included: /opt/ansible/roles/splunk_monitor/tasks/../../../roles/splunk_common/tasks/wait_for_splunk_instance.yml for localhost => (item=splunk-s1-standalone-0.splunk-s1-standalone-headless.default.svc.cluster.local)
Monday 08 February 2021  14:08:34 +0000 (0:00:00.067)       0:00:48.573 ******* 
FAILED - RETRYING: Check Splunk instance is running (60 retries left).
FAILED - RETRYING: Check Splunk instance is running (59 retries left).
FAILED - RETRYING: Check Splunk instance is running (58 retries left).
...

```

Any idea why?

**Comment by pogdin** [comment]
First guess.  I believe reverting to the Free license disables distributed search.  The Monitoring Console pod relies upon distributed search to communicate with the Standalone.

**Comment by pogdin** [comment]
Attempted to replicate.  The Monitoring Console pod actually comes back up in my environment but the Standalone is unreachable per my above comment.  We are considering moving the Monitoring Console into its own CRD, in which case, you could start a Standalone with the Free license without the MC present.  At this point, I would call it a bug or known limitation given the limits in the [Free License](https://docs.splunk.com/Documentation/Splunk/8.1.2/Admin/MoreaboutSplunkFree).

**Comment by lappodeveloper** [comment]
Thank you pogdin for the feedback!
Is maybe somehow possible to disable the monitoring console pod ?
