### ISSUE TITLE
Splunk Operator only accepts DNS Domain of "cluster.local"

### ISSUE THREAD

**Issue by crawdaddy18** [splunk/splunk-operator#248]
Issue: Splunk Operator will only work properly if K8S cluster is created with DNS Domain of "cluster.local".  Not all clusters will use this default DNS Domain.

**Comment by pogdin** [comment]
https://github.com/splunk/splunk-operator/blob/develop/docs/Install.md#cluster-domain

Let me know if this guidance is sufficient to close this issue.  Thanks.

**Comment by crawdaddy18** [comment]
Checking.  Thank you.

**Comment by crawdaddy18** [comment]
Solutions works.   Thank you.
