### ISSUE TITLE
Container Image Security

### ISSUE THREAD

**Issue by Kiran01bm** [splunk/splunk-operator#253]
Perhaps this is a generic question that applies to all Container images that Splunk distributes. 

From a Security Perspective - Is there a recommendation on where we can check for Security Posture (ex: if there are any known vulnerabilities etc) something like [Red Hats container Health Index](https://access.redhat.com/articles/2803031).

Did run a couple of quick scans on Quay for 
1. docker.io/splunk/splunk:8.1.0 - Looks good
2. docker.io/splunk/splunk-operator:0.2.0 - 23 known vulnerabilities per Quay Scan.

![splunk-operator-8 1-scan](https://user-images.githubusercontent.com/17925757/107453075-65b07500-6b9e-11eb-8456-27164a5c4fc3.png)
![splunk-operator-0 2 0-scan](https://user-images.githubusercontent.com/17925757/107453087-6812cf00-6b9e-11eb-960c-b0deb6f55ed0.png)

**Comment by pogdin** [comment]
Docker Hub does offer this as a service but we do not currently leverage it.  The Red Hat Container Registry does do this automatically, and we do try to keep the latest Operator and Splunk Docker Image up there:
https://catalog.redhat.com/software/containers/splunk/splunk/5df01cc529373831743c7062?container-tabs=security
https://catalog.redhat.com/software/containers/splunk/splunk-operator/5dcf27cc69aea35a1c2b4b01?container-tabs=security

**Comment by Kiran01bm** [comment]
Sure thank you. Couple of quick question in-terms release process:

1. Would any published GA image have no known vulnerabilities ex: like splunk/splunk:8.1.2 ?

2. On the Beta one's would you still release images with known open vulnerabilities ex: splunk/splunk-operator:0.2.0 has 33 in total (1 of Important category, 30 moderate and 2 of low severity) ?

**Comment by pogdin** [comment]
1. Splunk 8.1.2 is a GA container image so, yes, anything GA we would target zero vulns.
2. We'll continue to release Beta images with open issues but attempt to also push that to zero.

**Comment by pogdin** [comment]
Scanning enabled on https://hub.docker.com/r/splunk/splunk-operator
