### ISSUE TITLE
Go Error:  Two Different Modules Paths

### ISSUE THREAD

**Issue by crawdaddy18** [splunk/splunk-operator#27]
I am receiving an error when running "make":
go: github.com/munnerz/goautoneg@v0.0.0-20120707110453-a547fc61f48d used for two different module paths (bitbucket.org/ww/goautoneg and github.com/munnerz/goautoneg)

Per this link:  https://github.com/golang/go/issues/26904, the issue has to do with two branches that have not been merged?

**Comment by mikedickey** [comment]
This should work ok now on develop branch using operator-sdk 0.15.1

**Comment by crawdaddy18** [comment]
Thank you, the make starts now after switching to the "develop" branch, but I am getting the following error:

Running transaction test...
error: Error running transaction: package glibc-common-2.28-72.el8_1.1.x86_64 (which is newer than glibc-common-2.28-72.el8.x86_64) is already installed
package glibc-2.28-72.el8_1.1.x86_64 (which is newer than glibc-2.28-72.el8.x86_64) is already installed
package glibc-minimal-langpack-2.28-72.el8_1.1.x86_64 (which is newer than glibc-minimal-langpack-2.28-72.el8.x86_64) is already installed
The command '/bin/sh -c dnf install -y git make gcc findutils openssh tar gzip ca-certificates     && dnf clean all     && wget -O /usr/local/bin/operator-sdk ${OPERATOR_SDK_URL}     && chmod a+x /usr/local/bin/operator-sdk     && wget -O /tmp/docker-cli.rpm ${DOCKER_CLI_URL}     && rpm -ivh /tmp/docker-cli.rpm     && rm /tmp/docker-cli.rpm' returned a non-zero code: 1
make: *** [builder] Error 1

I have confirmed I am using operator-sdk 0.15.1

Chriss-MacBook-Pro:splunk-operator$ /usr/local/bin/operator-sdk version
operator-sdk version: "v0.15.1", commit: "e35ec7b722ba095e6438f63fafb9e7326870b486", go version: "go1.13.6 darwin/amd64"
