### ISSUE TITLE
Build Error on Develop Branch

### ISSUE THREAD

**Issue by crawdaddy18** [splunk/splunk-operator#30]
After being directed to move to the develop branch regarding a separate issue, I am having the following build error:

Running transaction test...
error: Error running transaction: package glibc-common-2.28-72.el8_1.1.x86_64 (which is newer than glibc-common-2.28-72.el8.x86_64) is already installed
package glibc-2.28-72.el8_1.1.x86_64 (which is newer than glibc-2.28-72.el8.x86_64) is already installed
package glibc-minimal-langpack-2.28-72.el8_1.1.x86_64 (which is newer than glibc-minimal-langpack-2.28-72.el8.x86_64) is already installed
The command '/bin/sh -c dnf install -y git make gcc findutils openssh tar gzip ca-certificates && dnf clean all && wget -O /usr/local/bin/operator-sdk ${OPERATOR_SDK_URL} && chmod a+x /usr/local/bin/operator-sdk && wget -O /tmp/docker-cli.rpm ${DOCKER_CLI_URL} && rpm -ivh /tmp/docker-cli.rpm && rm /tmp/docker-cli.rpm' returned a non-zero code: 1
make: *** [builder] Error 1

I have confirmed I am using operator-sdk 0.15.1

MacBook-Pro:splunk-operator$ /usr/local/bin/operator-sdk version
operator-sdk version: "v0.15.1", commit: "e35ec7b722ba095e6438f63fafb9e7326870b486", go version: "go1.13.6 darwin/amd64"

**Comment by mikedickey** [comment]
The develop branch is currently setup to build the operator inside a container. Kind of experimenting with that and may change back, but regardless of the "default" for `make all` you can be more explicit via these commands:

* `make image` - this will build the `splunk/splunk-operator` image locally using the go compiler and environment on your computer
* `make builder` - this can be used to create the container that is used to build the operator for the next command...
* `make builder-image` - this builds the operator inside of the builder container

Presumably, using the container to build should be more reliable and consistent, but the error you are reporting appears to come from the process of creating the build container (`make builder`). I tried running this on my mac with a clean image cache, and it worked fine. Only thing I can think is that you are hitting some RHEL/UBI package repository bug, or there was a random temporary outage or blip when you happened to try it. I'd try again, after pulling the latest UBI base image layers to reduce the likelihood of package conflicts: `docker pull registry.access.redhat.com/ubi8/ubi-minimal`

**Comment by crawdaddy18** [comment]
Thank you, the make image, make builder, and make builder-image worked.
