### ISSUE TITLE
Indexer Cluster CRD is in error state (Tanzu)

### ISSUE THREAD

**Issue by harikrishnant** [splunk/splunk-operator#310]
Hi Team

I am trying the splunk deployment on VMware Tanzu platform, however I am seeing the below error while deploying the indexer cluster. The CRD is in error state, any advice would be much appreciated:

[root@tkgcli tanzu]# kubectl get idc ic0
NAME   PHASE   MASTER   DESIRED   READY   AGE
ic0    Error   Ready    3         0       17m

[root@tkgcli tanzu]#
[root@tkgcli tanzu]# kubectl describe idc ic0
Name:         ic0
Namespace:    default
Labels:       <none>
Annotations:  API Version:  enterprise.splunk.com/v1
Kind:         IndexerCluster
Metadata:
  Creation Timestamp:             2021-04-08T17:34:59Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2021-04-08T17:35:54Z
  Finalizers:
    enterprise.splunk.com/delete-pvc
  Generation:  2
  Managed Fields:
    API Version:  enterprise.splunk.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:Mock:
        f:affinity:
        f:defaults:
        f:defaultsUrl:
        f:defaultsUrlApps:
        f:etcVolumeStorageConfig:
          .:
          f:ephemeralStorage:
          f:storageCapacity:
          f:storageClassName:
        f:image:
        f:imagePullPolicy:
        f:licenseMasterRef:
        f:licenseUrl:
        f:resources:
          .:
          f:limits:
            .:
            f:cpu:
            f:memory:
          f:requests:
            .:
            f:cpu:
            f:memory:
        f:schedulerName:
        f:serviceAccount:
        f:serviceTemplate:
          .:
          f:metadata:
            .:
            f:creationTimestamp:
          f:spec:
            .:
            f:type:
          f:status:
            .:
            f:loadBalancer:
        f:varVolumeStorageConfig:
          .:
          f:ephemeralStorage:
          f:storageCapacity:
          f:storageClassName:
        f:volumes:
      f:status:
        .:
        f:IdxcPasswordChangedSecrets:
        f:clusterMasterPhase:
        f:indexer_secret_changed_flag:
        f:indexing_ready_flag:
        f:initialized_flag:
        f:maintenance_mode:
        f:namespace_scoped_secret_resource_version:
        f:peers:
        f:phase:
        f:readyReplicas:
        f:replicas:
        f:selector:
        f:service_ready_flag:
    Manager:      splunk-operator
    Operation:    Update
    Time:         2021-04-08T17:34:59Z
    API Version:  enterprise.splunk.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:finalizers:
      f:spec:
        .:
        f:clusterMasterRef:
          .:
          f:name:
        f:replicas:
    Manager:         kubectl
    Operation:       Update
    Time:            2021-04-08T17:36:41Z
  Resource Version:  144959
  Self Link:         /apis/enterprise.splunk.com/v1/namespaces/default/indexerclusters/ic0
  UID:               7ed0fa6d-e416-4895-98cd-ebe9cf308340
Spec:
  Cluster Master Ref:
    Name:              cm
  Replicas:            3
  Storage Class Name:  vcf02-cwld01-c01-vsan-storage-policy
  Var Storage:         128Gi
Status:
  Idxc Password Changed Secrets:
  Cluster Master Phase:  Ready
  indexer_secret_changed_flag:
  indexing_ready_flag:                       false
  initialized_flag:                          false
  maintenance_mode:                          false
  namespace_scoped_secret_resource_version:
  Peers:
  Phase:               Error
  Ready Replicas:      0
  Replicas:            3
  Selector:            app.kubernetes.io/instance=splunk-ic0-indexer
  service_ready_flag:  false
Events:                <none>
[root@tkgcli tanzu]#

**Comment by gaurav-splunk** [comment]
Can you share your yaml files for ClusterMaster and IndexerCluster? Also, maybe look at operator logs to see if you get any hint of what the error might be about.

**Comment by harikrishnant** [comment]
Thanks for checking [Gaurav]

Here is what is see in the operator logs: There is a line that says "Could not get cluster info from cluster master" and "dial tcp: lookup splunk-cm-cluster-master-service.default.svc.cluster.local on 198.48.0.10:53: no such host" . 

Towards at the end are the  yamls used:

{"level":"info","ts":1617905720.3637238,"logger":"splunk.reconcile.Reconcile","msg":"Reconciling custom resource","Group":"enterprise.splunk.com","Version":"v1","Kind":"ClusterMaster","Namespace":"default","Name":"cm"}
{"level":"info","ts":1617905720.3781116,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-cm-indexer-service","namespace":"default"}
{"level":"info","ts":1617905720.3807964,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-cm-cluster-master-service","namespace":"default"}
{"level":"info","ts":1617905720.4017093,"logger":"splunk.reconcile.UpdateStatefulSetPods","msg":"All pods are ready","name":"splunk-cm-cluster-master","namespace":"default"}
{"level":"info","ts":1617905720.4098651,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-default-monitoring-console-service","namespace":"default"}
{"level":"info","ts":1617905720.4136662,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-default-monitoring-console-headless","namespace":"default"}
{"level":"error","ts":1617905720.427839,"logger":"splunk.reconcile.Reconcile","msg":"Reconciliation requeued","Group":"enterprise.splunk.com","Version":"v1","Kind":"ClusterMaster","Namespace":"default","Name":"cm","RequeueAfter":5,"error":"Get https://splunk-cm-cluster-master-service.default.svc.cluster.local:8089/services/cluster/config?count=0&output_mode=json: dial tcp: lookup splunk-cm-cluster-master-service.default.svc.cluster.local on 198.48.0.10:53: no such host","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgo/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/splunk/splunk-operator/pkg/splunk/controller.splunkReconciler.Reconcile\n\tsplunk-operator/pkg/splunk/controller/controller.go:125\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1617905723.6379027,"logger":"splunk.reconcile.Reconcile","msg":"Reconciling custom resource","Group":"enterprise.splunk.com","Version":"v1","Kind":"IndexerCluster","Namespace":"default","Name":"ic1"}
{"level":"error","ts":1617905723.6832235,"logger":"splunk.reconcile.Reconcile","msg":"Reconciliation requeued","Group":"enterprise.splunk.com","Version":"v1","Kind":"IndexerCluster","Namespace":"default","Name":"ic1","RequeueAfter":5,"error":"Could not get cluster info from cluster master","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgo/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/splunk/splunk-operator/pkg/splunk/controller.splunkReconciler.Reconcile\n\tsplunk-operator/pkg/splunk/controller/controller.go:125\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}


Yaml


[root@tkgcli tanzu]# cat splunkcm.yaml
apiVersion: enterprise.splunk.com/v1
kind: ClusterMaster
metadata:
  name: cm
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  etcVolumeStorageConfig:
    storageClassName: vcf02-cwld01-c01-vsan-storage-policy
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: vcf02-cwld01-c01-vsan-storage-policy
    storageCapacity: 25Gi
[root@tkgcli tanzu]#

---

[root@tkgcli tanzu]# cat splunkcm.yaml
apiVersion: enterprise.splunk.com/v1
kind: ClusterMaster
metadata:
  name: cm
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  etcVolumeStorageConfig:
    storageClassName: vcf02-cwld01-c01-vsan-storage-policy
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: vcf02-cwld01-c01-vsan-storage-policy
    storageCapacity: 25Gi
[root@tkgcli tanzu]# cat splunkic.yaml
apiVersion: enterprise.splunk.com/v1
kind: IndexerCluster
metadata:
  name: ic1
spec:
  replicas: 3
  etcVolumeStorageConfig:
    storageClassName: vcf02-cwld01-c01-vsan-storage-policy
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: vcf02-cwld01-c01-vsan-storage-policy
    storageCapacity: 50Gi
  clusterMasterRef:
    name: cm
[root@tkgcli tanzu]#

**Comment by harikrishnant** [comment]
Hello Gaurav, The indexer cluster is now up and running. Thanks a lot for your time and support, really appreciate it. 

The issue was with a case mismatch between the Tanzu DNS zone and the splunk operator default cluster domain which has been corrected now.

[root@tkgcli tanzu]# kubectl get all
NAME                                      READY   STATUS    RESTARTS   AGE
pod/hello-5864564bc7-x7bfw                1/1     Running   0          31m
pod/splunk-cm-cluster-master-0            1/1     Running   0          14h
pod/splunk-default-monitoring-console-0   1/1     Running   0          5m26s
pod/splunk-ic1-indexer-0                  1/1     Running   0          5m26s
pod/splunk-ic1-indexer-1                  1/1     Running   0          5m26s
pod/splunk-ic1-indexer-2                  1/1     Running   0          5m26s
pod/splunk-operator-7d59d8ddb4-vmdhs      1/1     Running   0          5m52s
