### ISSUE TITLE
splunk-operator Helm chart

### ISSUE THREAD

**Issue by jfusterm** [splunk/splunk-operator#318]
Are you planning on creating a Helm Chart to install the `splunk-operator`?

I've created one to use it at work so if you are interested, I'll be glad to open a PR with the chart.

Best regards.

**Comment by frajuqeb** [comment]
we have also created a helm chart for our test deployment of the operator

**Comment by AkshayDubey29** [comment]
@frajuqeb Can I get the link for the helm chart, would like to test the same.

**Comment by vzabawski** [comment]
Helm chart would really make the process of installation easier. :)

**Comment by pogdin** [comment]
Delivered in [2.1.0](https://github.com/splunk/splunk-operator/blob/main/docs/ChangeLog.md#210-2022-11-22)
