### ISSUE TITLE
Can I use only the Search Head Resource in my existing Splunk Architecture? 

### ISSUE THREAD

**Issue by leandropadua** [splunk/splunk-operator#327]
This is a clarification issue. I'm running a kubernetes cluster with Splunk components being deployed as standard statefulsets. I'm interesting in starting using the operator, but I don't want to switch everything to be managed by the operator yet. 

I would like to start with the Search Head Cluster first and eventually I use the others CRDs.
The examples docs are not clear if that is possible. It does mention [an example where an external indexer cluster is used](https://github.com/splunk/splunk-operator/blob/develop/docs/Examples.md#using-an-external-indexer-cluster), but scenario is kind of the opposite. An existing Splunk Architecture to use only the Search Head cluster CRD.
Thanks

**Comment by pogdin** [comment]
Hi, yes, we say in those docs "The Splunk Operator for Kubernetes allows you to use an external cluster of indexers with its Standalone, SearchHeadCluster and LicenseMaster resources."  Which, if I understand correctly, is what you are trying to do.  Use an Operator created SHC against a non-Operator Indexer Cluster(s) or set of Indexers.  At this point, we would encourage you to experiment in a test deployment with this scenario but would discourage you from attempting this in production.  The Operator obviously automates a lot of the SHC -> IDXC communication and password/key sharing and I'm not positive we've accounted for all scenarios when self-managing these.  Please let us know if you hit any problems if you choose to experiment and we'll take up some experimentation ourselves in an upcoming sprint.  To be sure, these mixed scenarios are deployment methods we would like to fully support over time but need to make sure there are no overly rough edges.
