### ISSUE TITLE
would like to be able to install different apps on the cluster manager and the indexers

### ISSUE THREAD

**Issue by frajuqeb** [splunk/splunk-operator#339]
We're currently trying out the splunk-operator and it appears there isn't an obvious way to install different apps on the cluster manager and on the indexers. Is this a feature that could be added to an upcoming release?

**Comment by pogdin** [comment]
Hi, thanks for your question.  There is not a straightforward way to achieve this today but we are actually currently working on an updated App Install/Management framework that would permit this.  Should be ready for preview in a few months.  Just curious, what kind of App are you using that is scoped to the CM only?

**Comment by frajuqeb** [comment]
All of our custom conf files are contained in an org/company app. Those conf files are a bit different on the CM than on the indexers.

**Comment by ashurack** [comment]
+1 on this request

The CM is essentially a SH.  In normal on-prem environments, the IDX's receive tuned configurations.  These specifically...we would not want to deploy to the CM.

```
# web.conf
[settings]
startwebserver = 0

# server.conf
[kvstore]
disabled = true

# limits.conf
[scheduler]
saved_searches_disabled = true
```

**Comment by pogdin** [comment]
Delivered with `scope` of local or cluster with https://github.com/splunk/splunk-operator/blob/master/docs/AppFramework.md
