### ISSUE TITLE
would like the monitoring console to be more customizable

### ISSUE THREAD

**Issue by frajuqeb** [splunk/splunk-operator#346]
* We'd like to be able to install apps on the monitoring console (& only the monitoring console).
* We'd like to configure alerts on the monitoring console from the yaml.
* We'd like to configure the monitoring console to monitor other splunk clusters.

**Comment by pogdin** [comment]
**Hi, thanks for your requests.  A couple of clarifying questions please:**
- We'd like to be able to install apps on the monitoring console (& only the monitoring console). **This makes total sense and should be achievable as we move the MC to its own CRD later this year.**
- We'd like to configure alerts on the monitoring console from the yaml. **Would it be ok to configure the alerts in an App that you pass to the MC instance?**
- We'd like to configure the monitoring console to monitor other splunk clusters. **Would these other clusters be in the same namespace as the MC, different namespace as MC but same k8s cluster, or entirely different k8s cluster?  Thanks.**

**Comment by frajuqeb** [comment]
Would it be ok to configure the alerts in an App that you pass to the MC instance? Yes, we can easily work with this, thank you.
Would these other clusters be in the same namespace as the MC, different namespace as MC but same k8s cluster, or entirely different k8s cluster? These other clusters may not be running in kubernetes, they will always be entirely different k8s clusters.

**Comment by pogdin** [comment]
Delivered with [MC CRD](https://github.com/splunk/splunk-operator/blob/master/docs/CustomResources.md#monitoringconsole-resource-spec-parameters).
