### ISSUE TITLE
Smart Store, Replication Factor and Search Factor

### ISSUE THREAD

**Issue by rajeshvijayarajan** [splunk/splunk-operator#352]
I see the Smart Store documentation states that the Replication Factor (RF) and Search Factor (SF) need to match for the functionality to work. See section 'Current restrictions of Smart Store use'
https://docs.splunk.com/Documentation/Splunk/latest/Indexer/AboutSmartStore

I also see that use of Smart Store is mandated with Splunk on k8s, yet the default RF is 3 and SF is 2. 

When I put the two together, may be we need to have the right defaults in place?

Thoughts?

**Comment by pogdin** [comment]
Hi, I believe we are shipping with RF/SF=3.  Let me know if you are showing otherwise.  Thanks.
<img width="504" alt="Screen Shot 2021-05-27 at 10 20 50 AM" src="https://user-images.githubusercontent.com/2925186/119843283-6531b500-bed5-11eb-9e29-760fc1a2c263.png">

**Comment by rajeshvijayarajan** [comment]
Thanks @pogdin ! And sorry for the delay in reverting back. 
Am closing this issue, you are right. I saw the abnormality because of the issues in my smart store configuration. The replication and search factors weren't being met. Now that those issues have been resolved, i do see that the default is set to 3 for both.

Cheers!
