### ISSUE TITLE
Feature Request: Allow setting environment variables on CRD objects

### ISSUE THREAD

**Issue by jkoby** [splunk/splunk-operator#363]
The CRD specs allow for customizations to default.yml to affect the Ansible playbook, but there isn't a straightforward way to set environment variables of the underlying pods directly on a Standalone object, or any of the other CRD objects.

This would involve exposing an (optional) EnvVar object (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#envvar-v1-core) as an additional field in the Standalone CRD spec, and having the Operator merge it with the resulting ReplicaSet's PodTemplate.

**Comment by pogdin** [comment]
Please let me know if [this](https://github.com/splunk/splunk-operator/pull/325) recent pull request addresses the requirement.

**Comment by jkoby** [comment]
That PR (https://github.com/splunk/splunk-operator/pull/325) would address the requirement, yes.
