### ISSUE TITLE
Request for working example configurations

### ISSUE THREAD

**Issue by adamrushuk** [splunk/splunk-operator#379]
Although you have good documentation so far, it would be great to have an `/examples` folder - or even a separate examples repo, like Argo CD have done here: https://github.com/argoproj/argocd-example-apps.

The folder would contain validated working examples for different configurations, eg:

- `/examples/standalone/standalone.yaml`
- `/examples/clustered01/licensemaster.yaml`
- `/examples/clustered01/clustermaster.yaml`
- `/examples/clustered01/indexercluster.yaml`

There could even be specific examples for each cloud platform, eg:

- `/examples/azure/standalone/standalone.yaml`
- `/examples/aws/standalone/standalone.yaml`

I'm struggling to get a clustered deployment working following these instructions: https://github.com/splunk/splunk-operator/blob/develop/docs/Examples.md#creating-a-clustered-deployment so it would be great to work with you guys to get a working configuration, then other users could simply run `kubectl apply -f examples/clustered01/`.

**Comment by BGrasnick** [comment]
I also had some problems with the clustered installation and therefore proposed https://github.com/splunk/splunk-operator/pull/354

You can find my fix (to the splunk-operator-cluster.yaml) here:
https://github.com/splunk/splunk-operator/issues/206#issuecomment-785076863

Hope this helps.

**Comment by adamrushuk** [comment]
Hi @BGrasnick, I'm not sure your issues are the same as mine, as I've been using the [Non-admin Installation method](https://github.com/splunk/splunk-operator/blob/develop/docs/Install.md#installation-using-a-non-admin-user):

```bash
# create namespace
kubectl create namespace sok

# an admin needs to install the CRDs
kubectl apply --namespace sok -f https://github.com/splunk/splunk-operator/releases/download/1.0.1/splunk-operator-crds.yaml

# install splunk operator into namespace
kubectl apply --namespace sok -f https://github.com/splunk/splunk-operator/releases/download/1.0.1/splunk-operator-noadmin.yaml
```

In my testing I can spin up a LicenseMaster, ClusterMaster, and a IndexerCluster. The problem is that the indexer peers cannot connect to the ClusterMaster.

I'd be happy to work with others in getting a validated configuration working for common deployments.

**Comment by pogdin** [comment]
Thanks for the feedback.  We did add a few of the clustered examples [here](https://github.com/splunk/splunk-operator/tree/develop/deploy/examples/advanced) but I agree we could add more.

**Comment by adamrushuk** [comment]
Thanks @pogdin I didn't know about https://github.com/splunk/splunk-operator/tree/develop/deploy/examples/advanced
The c1 example worked as expected 👍🏼
