### ISSUE TITLE
Change CRD names and spec to match docs (master vs manager, etc)

### ISSUE THREAD

**Issue by jkoby** [splunk/splunk-operator#387]
The CRD resources and YAML specs currently use the older non-preferred terminology of LicenseMaster, ClusterMaster, etc.

Documentation has been updated throughout docs.splunk.com to reflect "cluster manager" and "license manager" as preferred terms.  The change in CRD names may cause trouble for existing installations to migrate; ClusterMaster and ClusterManager would likely need to remain in parallel use for some time, for example.

**Comment by pogdin** [comment]
Yep, I would very much like to have this done in the next few months.  Thanks.

**Comment by mgaldino-splunk** [comment]
Starting in the 2.1.0 release, we now support ClusterManager and LicenseManager CRDs and have updated the documentation, examples, and testing code to support the newly introduced CRDs. There's also a migration script where existing CM and LM can be upgraded to a non-bias language version. 

More details in https://github.com/splunk/splunk-operator/blob/develop/docs/BiasLanguageMigration.md
