### ISSUE TITLE
Local persistence storage and Replica affinity to node

### ISSUE THREAD

**Issue by layavadi** [splunk/splunk-operator#393]
While using Local persistent volume, we need to ensure that replicas don't end up on the same node. Is there a way to assign affinity(Anti-Affinity) to replica pods so that they don't end up on the same node ?

**Comment by pogdin** [comment]
Thanks for submitting.  I know there is a web server/redis example of anti-affinity in the [k8s docs](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#always-co-located-in-the-same-node) but we've not experimented with this yet or have Splunk-specific guidance.  Will add to docs backlog.

**Comment by layavadi** [comment]
Well it is not just affinity/Antiaffinity at POD level with 1 container each. WIth K8 I can bring up many pods as and when capacity is needed . Idea is to make sure that replicas don't end up on the same host ..  We can have multiple PODS of an indexers on the same node provided its replicas are not on the same node.

**Comment by singar1975** [comment]
Hi,

I too have same question. Are there any conclusion so far or any enhancement planned for Cluster Manager ? I would say, containerized Cluster Manager should have the knoweledge of K8s worker nodes and make sure that it always instructs indexer to send the replicated hot bucket data to target peers, located at different worker nodes as much as possible. This will make sure that we don't end up loosing hot bucket data where the source copy and replicated copies are all on same worker node and the woker node goes down.

**Comment by akondur** [comment]
Hi @layavadi / @singar1975 , is this issue concerning only Indexer Clusters. If yes, we have examples of multi-site indexer clustering [here](https://github.com/splunk/splunk-operator/blob/master/docs/MultisiteExamples.md) where we can deploy each indexers to a different site which would be on a different node. Please let us know.

**Comment by akondur** [comment]
Closing as multi-site indexer clustering is configurable via the operator. Please re-open if the problem still exists.
