### ISSUE TITLE
Use release version of CRD

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#402]
CRD's have long been release however Splunk-operator continues to use beta api definitions
```
  warning: apiextensions.k8s.io/v1beta1/CustomResourceDefinition is deprecated by apiextensions.k8s.io/v1/CustomResourceDefinition and not supported by Kubernetes v1.22+ clusters.
```

**Comment by rfaircloth-splunk** [comment]
K8s 1.22 is scheduled to be released next month Splunk operator will no longer work on new k8s releases
Wednesday, August 4th: Week 15 - Kubernetes v1.22.0 release

**Comment by akondur** [comment]
Closing as per this [comment](https://github.com/splunk/splunk-operator/issues/495#issuecomment-998321013).
