### ISSUE TITLE
Configuring SAML authentication

### ISSUE THREAD

**Issue by bchen-nydig** [splunk/splunk-operator#432]
Hello,

What is the recommended means for us to configure SAML?  We need the hooks to configure and persist

`/opt/splunk/etc/system/local/authentication.conf`

Any recommendations?

Thanks!

-bc

**Comment by pogdin** [comment]
Hi, thanks for submitting.  The basic answer here is to pass it in via an [App](https://github.com/splunk/splunk-operator/blob/develop/docs/Examples.md#installing-splunk-apps) since there is no special handling at the CRD level.

**Comment by akondur** [comment]
Hi @bchen-nydig , please let us know if using an app for `authentication.conf` works for you. 

@vzabawski Currently our configurations for Splunk instances are CR specific and you can point the CRs to a specific app. Could you describe the example with several instances in detail?

**Comment by vzabawski** [comment]
Hi @akondur. In my case I had 3 Splunk instances. Let's call them "splunk-a", "splunk-b" and "splunk-c". The configuration was 90% identical except entity id. It should be different for each instance. I solved this problem by writing a script which generates an archive with config file containing entity id I need.

**Comment by enenum** [comment]
I am looking for how to setup saml authentication during cluster install where Splunk Enterprise is installed (ansible based) with the operator. It seems that this is the topic of discussion here.

I can manually setup SAML over the UI, but that is by visiting each pod to set it up. I am looking for a way to place config files like authentication.conf, certs, etc, such that every pod comes up with the SAML authentication setup, even pods that are added during scale up.

The mention of splunk app looked promising, but i do not see how I can place a file in the existing $SPLUNK_HOME/etc/system/local/ with mounts. As soon as I attempt to use the volume for app, the file is under /mnt/<blah> - I saw the mnt can be configured to point elsewhere, but what is working already expects it that way.

Sorry for my noob frazzled face, but I hope someone can show the way. Thank you in advance

**Comment by vzabawski** [comment]
You need to create a custom Splunk app and deploy it on Splunk. No need to remount "apps" dir.
Create Splunk app skeleton: https://dev.splunk.com/enterprise/docs/developapps/createapps
Place configs with values you want, package them: https://dev.splunk.com/enterprise/docs/releaseapps/packageapps/
Install using the following guide: https://github.com/splunk/splunk-operator/blob/develop/docs/Examples.md#installing-splunk-apps

**Comment by iaroslav-nakonechnikov** [comment]
@vzabawski can you share a bit more info how you work with dynamic setup? 

for example, we have Splunk in several envs, and don't want to use single saml setup everywhere. So need to have a way to create apps, which supports dynamic/semi-dynamic configuration.
