### ISSUE TITLE
Indexer cluster not coming up in a Splunk clustered deployment

### ISSUE THREAD

**Issue by sisudhir** [splunk/splunk-operator#446]
I'm referring to the following link for configuring splunk enterprise deployment: https://splunk.github.io/splunk-operator/Examples.html#creating-a-clustered-deployment
My yaml for creating a CM and IDC looks like this:
apiVersion: enterprise.splunk.com/v2
kind: ClusterMaster
metadata:
  name: test-cm
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  etcVolumeStorageConfig:
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageCapacity: 25Gi
---
apiVersion: enterprise.splunk.com/v2
kind: IndexerCluster
metadata:
  name: test-idc
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterMasterRef:
    name: test-cm
  replicas: 3
  etcVolumeStorageConfig:
    storageCapacity: 10Gi
  varVolumeStorageConfig:
    storageCapacity: 100Gi

The apply goes through successfully (without throwing any error), but the indexer pods wouldn't show up:
**% kubectl get pods**
NAME                                          READY   STATUS    RESTARTS   AGE
splunk-operator-5845f6d45c-j472b              1/1     Running   0          16h
splunk-splunk-operator-monitoring-console-0   1/1     Running   0          114m
splunk-test-cm-cluster-master-0               1/1     Running   0          116m

**% kubectl get pvc**
NAME                                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc-etc-splunk-test-cm-cluster-master-0   Bound    pvc-58ce731a-314c-41af-aaea-58d9a63cb043   10Gi       RWO            local-path     118m
pvc-var-splunk-test-cm-cluster-master-0   Bound    pvc-75242b06-fc98-4fc4-94f7-6d1983f348db   100Gi      RWO            local-path     118m

**% kubectl get idc**
_NAME       PHASE   MASTER   DESIRED   READY   AGE
test-idc                                      94m_

**% kubectl get cm**
NAME                                        DATA   AGE
splunk-splunk-operator-monitoring-console   1      116m_

Looks like cluster master ref is not available for idc from the operator pod log. Pls find the operator-log and cluster-master-log txt files attached herewith.
But the cluster master reference is seen in the description of test-idc:

**% kubectl describe idc test-idc**
Name:         test-idc
Namespace:    splunk-operator
Labels:       <none>
Annotations:  <none>
API Version:  enterprise.splunk.com/v2
Kind:         IndexerCluster
Metadata:
  Creation Timestamp:  2021-07-29T06:29:14Z
  Generation:          2
  Managed Fields:
    API Version:  enterprise.splunk.com/v2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:clusterMasterRef:
          .:
          f:name:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2021-07-29T06:30:05Z
  Resource Version:  2499131
  Self Link:         /apis/enterprise.splunk.com/v2/namespaces/splunk-operator/indexerclusters/test-idc
  UID:               7d4cef19-ebb9-44f8-9a6d-24dce94afccb
Spec:
  _Cluster Master Ref:
    Name:  test-cm_
Events:    <none>

Not sure, what could be missing here. Any help/pointers would be very helpful! Appreciate your responses and pointers! 

PS: Just to give a little backgroud on my setup. I'm using **IKS (Cisco Intersight Kubernetes Service) container platform and Rancher's local storage path provisioner**. I don't see any issue with the local storage path dynamic provisioner though, just wanted to keep you informed on the setup on which I'm trying the Splunk Operator. Also, I'm using **Splunk operator version 1.0.1**.
[splunk-operator-log.txt](https://github.com/splunk/splunk-operator/files/6898990/splunk-operator-log.txt)
[splunk-test-cm-cluster-master-0.txt](https://github.com/splunk/splunk-operator/files/6899001/splunk-test-cm-cluster-master-0.txt)

**Comment by pogdin** [comment]
Hi, thanks for submitting.  In these situations where we see the CM and IDX unable to communicate, sometimes it is networking.  Check the Cluster Domain. https://github.com/splunk/splunk-operator/blob/develop/docs/Install.md#cluster-domain

**Comment by sisudhir** [comment]
Hi, thank you for your prompt response! I added my domain in splunk-operator-install.yaml as an env entry. But I still see the same issue. My setup is behind a corporate firewall, so I've added the required proxy information in each of the nodes. Please let me know if there are any debugging steps that I can follow to get to the bottom of this issue. Appreciate your help!

**Comment by pogdin** [comment]
Try using `apiVersion: enterprise.splunk.com/v1`

**Comment by sisudhir** [comment]
This worked! thank you so much..

**Comment by layavadi** [comment]
Why does documentation points to v2 ?
