### ISSUE TITLE
Transparent Huge Pages disabled with Busybox not working anymore.

### ISSUE THREAD

**Issue by felipesewaybricker** [splunk/splunk-operator#450]
Hey guys, anyone with the zombied search problem?

The cause is the Transparent Huge Pages from the kernel, but i cant disable him now.

Any Tips?

initContainers:
    - name: disable-thp
      image: busybox
      volumeMounts:
        - name: host-sys
          mountPath: /host-sys
      command: ["sh", "-c", "echo never >/host-sys/kernel/mm/transparent_hugepage/enabled"]

**Comment by vzabawski** [comment]
I guess THP can be disabled on k8s node only, so you need either to run a container in privileged mode or disable THP some other way, e.g. by creating a special systemd service on k8s node which runs on startup and disabled THP.

**Comment by akondur** [comment]
Hi @felipesewaybricker , are you using the Splunk operator to deploy your containers via Splunk Enterprise CRs?

If yes, could you give us a clear description of the topology used with the operator and where the config [above](https://github.com/splunk/splunk-operator/issues/450#issue-959198336) comes into the picture?

**Comment by akondur** [comment]
Hi @felipesewaybricker , could you provide us more input as per this [comment](https://github.com/splunk/splunk-operator/issues/450#issuecomment-1084984164)?

**Comment by akondur** [comment]
Hi @felipesewaybricker , closing the issue for now. Please re-open if the issue still persists.
