### ISSUE TITLE
enterprise.splunk.com/v2 not available with docker desktop for mac

### ISSUE THREAD

**Issue by TheFausap** [splunk/splunk-operator#461]
Hello,

I tried to create a stand-alone splunk, after I installed the latest operator release 1.0.1, using the example yaml in the getting started guide, but it failed complaing the kind "Standalone" was not present in the group enterprise.splunk.com/v2

I "fixed" it using the group enterprise.splunk.com/v1

I'm using docker desktop under mac with the embedded kubernetes support.

Is this expected under this platform?

thanks
Fausto

**Comment by pogdin** [comment]
Hi, yes. The v2 is the develop branch and will be released with 1.0.2 shortly.  You should continue to use v1 until 1.0.2 drops.  Thanks.

**Comment by TheFausap** [comment]
> Hi, yes. The v2 is the develop branch and will be released with 1.0.2 shortly. You should continue to use v1 until 1.0.2 drops. Thanks.

It makes totally sense, but maybe it's better to update the getting started documentation at https://splunk.github.io/splunk-operator/
You have there a reference, in the example, to v2
