### ISSUE TITLE
Optionally expose additional ports on service

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#47]
Certain apps such as webhooks may require additional customer ports provide a way to indicate that should be exposed on the service definitions

**Comment by mikedickey** [comment]
Seems like this should be pretty easy to do using `serviceTemplate` but currently the code in `GetSplunkService()` overwrites any values for ports specified by user. It probably should use `append()` instead. Also, you may need to modify the PodTemplate for any corresponding StatefulSet for this to work as expected. We'll need to see if there is a clean way to do this without having to add more config parameters to CRDs..

**Comment by rfaircloth-splunk** [comment]
Yes I looked at ServiceTemplate but with no example I did not grok it
