### ISSUE TITLE
spec for Cluster resources, spark, idx, shc should separate master from peers 

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#49]
When providing the resource spec for cpu/mem/disk need to provide a separate configuration for "master" roles typical deployer for SHC is 2 core 2 GB typical indexer cm is 8 core 128gb

**Comment by mikedickey** [comment]
Same likely applies for disk: etcStorage and varStorage.

**Comment by rfaircloth-splunk** [comment]
Yes, etc is probably about the same on both but var certainly would not be

**Comment by Caldas** [comment]
That is really interesting

**Comment by themrkeys** [comment]
This issue is becoming a blocker can we get a small release with this change?

**Comment by akondur** [comment]
Closing the issue as we are able to [configure spec parameters](https://github.com/splunk/splunk-operator/blob/master/docs/StorageClass.md#setting-up-a-persistent-storage-for-splunk) for the etc and var persistent volumes. Please use `etcVolumeStorageConfig` and `varVolumeStorageConfig`.
