### ISSUE TITLE
Using EFS CSI or FSxLustre

### ISSUE THREAD

**Issue by cicsyd** [splunk/splunk-operator#491]
Hi,

We're looking to deploy a Splunk cluster in AWS EKS, but use EFS for persistent storage, specifically for the Splunk Master and other non clustered portions so that if we lose any AZ, the master can seamlessly move to another one.

Currently we have run into an issue where the CSI will have permission issues because it creates the PVC with a random UID and currently splunk creates them with a hard coded UID
https://github.com/splunk/splunk-operator/issues/242

There was also a recommendation to use EFS from here but not much info beyond that and we were unable to find any further info from the Splunk slack either:
https://github.com/splunk/splunk-operator/issues/364

We're also looking at FSx/Lustre as an alternative but yet to test

What's the best way forward for this?

Thanks

**Comment by pogdin** [comment]
Not something we've tried ourselves before but I see where you are going.  For testing purposes, can you overcome the UID problem by running Splunk as root?  The Ansible [defaults](https://github.com/splunk/splunk-ansible/blob/develop/docs/advanced/default.yml.spec.md) allow you specify which user and group to run Splunk as.  Obviously not suggested in production.

In that post regarding EFS, that was simply a workaround to get Splunk to stop complaining about the filesystem Fargate was passing.  EFS uses NFS which should allow Splunk to start and does not require the unsupported OPTIMISTIC_ABOUT_FILE_LOCKING flag.  We've historically been hesitant to suggest NFS for indexer storage and in fact I think the docs say we don't support it for hot/warm buckets.  But in this scenario, you're trying to  use it for the Cluster Manager if I understand correctly which may not have the same performance requirements as say an Indexer Cluster node.

If you could configure an EFS volume with decent performance, it would be interesting to try this.  Like I mentioned, not something we have tested internally yet.

**Comment by cicsyd** [comment]
Yes that's correct, we only intend on using this for things like the cluster/licence master and potentially a single search head (if possible), as the indexers can be clustered and make use of smartstore, so there's no need to look at it there.

As for the ansible defaults specifying the UID and GID, how would we pass those parameters into the splunk operator?

Thanks

**Comment by pogdin** [comment]
I was thinking you could use something like:

````
apiVersion: enterprise.splunk.com/v2
kind: Standalone
metadata:
  name: s1
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterMasterRef:
    name: cm-example
  licenseMasterRef:
    name: lm-example
  defaults: |-
    splunk:
      user: root
      group: 0
````

But in my brief testing that does not appear to work.  Perhaps there also needs to be a "run as root" flag on the cluster?

**Comment by akondur** [comment]
Hi @cicsyd , as of now the **docker-splunk** project supports only three users **ansible(999), splunk(41812) or root(0)** as per the security [documentation](https://github.com/splunk/docker-splunk/blob/develop/docs/SECURITY.md). The Splunk Operator hardcodes UID/GID of the container as **41812** as that is the recommended user/group for production. If **root(0)** or **ansible(999)** need to be configured on containers by the operator for testing purposes a custom image can be built by making a change to the **PodSecurityContext** [here](https://github.com/splunk/splunk-operator/blob/7098178a23c4a51f81f20027ecf0be7b0821b0e1/pkg/splunk/enterprise/configuration.go#L704).

Until **docker-splunk** adds support for dynamic users, the Splunk Operator is unable to pass over any configuration via K8s for a random UID to be set as UID/GID of the container. If such a docker-splunk enhancement is implemented, making the **podSecurityContext** configurable via CR spec will be considered.

Closing the issue as its out of scope of the operator at the moment.
