### ISSUE TITLE
Cluster peers do not require persitance

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#50]
In the current generated deployment both etc and var create pvc for etc and var, however, replication means this is not required. Provide a means to disable generation of pv mounts to use ephemeral storage instead.

**Comment by mikedickey** [comment]
I think persistent volumes are required regardless of replication. I suspect what you may be looking for is [Local Persistent Volumes](https://kubernetes.io/docs/concepts/storage/volumes/#local).

**Comment by themrkeys** [comment]
emptydir would be just fine for indexers protected by smartstore
https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

**Comment by mikedickey** [comment]
Maybe fine for experimentation, but I wouldn't feel comfortable with anyone using emptydir in production. Even with SmartStore, Splunk Enterprise has a long way to go before I think we could get that to work well.

**Comment by Caldas** [comment]
I agree with @mikedickey

**Comment by Caldas** [comment]
Hey @rfaircloth-splunk can we close this issue?
