### ISSUE TITLE
Replication strategy

### ISSUE THREAD

**Issue by rajeshvijayarajan** [splunk/splunk-operator#500]
Team,

I wanted some insight into the internals of replication. I believe the default configuration has the RF set to 3. In my setup I have observed that the indexer pods are scheduled such that they are evenly spread to the extent possible on all the k8s workers in the cluster. For e.g. if had 7 k8s worker hosts, and i set the replica count of the IndexerCluster to 7, a pod would get scheduled in each of the workers, if i chose 14, there would be 2 on each worker, and so on. 

With this background, can you help me understand what is the strategy used to determine the peers for replication? Is it guaranteed to the extent possible that an indexer would not replicate to a peer that is also scheduled on the same worker host? We are trying to determine the impact of this on the availability of the cluster, and also if there are possible scenarios where data loss can occur? 

Also, I would like to understand the improved reliability brought by the SmartStore architecture. Is the replication between the indexer (hot/warm) and the SmartStore (cold) asynchronous? Does the SmartStore eliminate the data loss possibility? Even if an indexer and the peers it was replicating to went down, would a copy be a guaranteed to be available in the S3 object store? 

Your insights are appreciated. Cheers!

**Comment by pogdin** [comment]
Hi @rajeshvijayarajan.  I believe most of the information you are looking for is within the standard Splunk docs.  At this point we're not enforcing any kind of node affinity or anti-affinity within the Splunk Operator when deploying an indexer cluster.  The basic guidance for availability/survive-ability still holds that the [cluster can tolerate a failure of (replication factor - 1) peer nodes](https://docs.splunk.com/Documentation/Splunk/8.2.2/Indexer/Thereplicationfactor#Replication_factor_and_cluster_resiliency).  The use of SmartStore does affect the replication factor of [warm buckets](https://docs.splunk.com/Documentation/Splunk/8.2.2/Indexer/IndexerclusteroperationsandSmartStore#Replication_factor_and_replicated_bucket_copies) and the warm bucket availability is ceded to the remote store but we still suggest following the rep factor - 1 guidance for maximum hot bucket availability.  This translates into the k8s world as "don't schedule multiple indexer cluster pods per k8s node where the loss of that node would violate the rep factor - 1 rule".

To your questions regarding SmartStore, the replication between the indexer node and the SmartStore volume occurs as the hot bucket rolls to warm.  Portions of the warm bucket are retained locally per the [cache manager's eviction strategy](https://docs.splunk.com/Documentation/Splunk/8.2.2/Indexer/SmartStorecachemanager).  SmartStore does not eliminate the possibility of data loss on the hot buckets per above and the availability of the warm buckets is shifted to the availability of the S3 location.

Hope this helps.

**Comment by rajeshvijayarajan** [comment]
Thanks @pogdin !
With the default RF of 3, the cluster can afford to lose 2 indexing peers. However, with you stating that the operator is not enforcing any node affinity or anti-affinity rules, am I right in assuming that there is a remote possibility of an indexer pod and its peers getting scheduled on the same k8s node?
 
And does this imply that the implementation in its current form, wouldn't advise packing more than 2 indexer pods (with 2, at least one peer is guaranteed to be in another k8s node) when deploying in production?

**Comment by pogdin** [comment]
No problem!  This scenario also assumes that the peers or indexer pods are gone entirely like if you were using local ephemeral or a local PVC.  If the PVC is on a network, you could likely have a higher indexer pod count/k8s node given that if the node fails, and there are enough remaining resources to schedule the pod elsewhere, it should come back up and re-attach to the PVC.

**Comment by rajeshvijayarajan** [comment]
Very good point on the usage of shared storage!

**Comment by akondur** [comment]
Closing as the comments above have provided sufficient explanation.
