### ISSUE TITLE
Support kube2iam and other annotation ext

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#51]
For any pod created to provide the ability to  enhance the meta for example with an indexer peer if using aws it will be common to use kube2iam so that annotations of iam role can be added to the node allowing access to S2 without the risky use of key/secrets

**Comment by mikedickey** [comment]
With 0.1.0, any annotations or labels you give to the CRs should get copied to all the pods created. Is this what you are looking for?

**Comment by themrkeys** [comment]
I think that will do let me test

**Comment by Caldas** [comment]
Hey, @themrkeys did your tests worked?
