### ISSUE TITLE
Monitoring console reports low disk space, disables search

### ISSUE THREAD

**Issue by djschaap** [splunk/splunk-operator#520]
After installing a simple standalone system in my lab and letting it run for a few hours, the monitoring console has started reporting low disk space (less than 5,000 MB free) and stopped allowing searches.

/opt/splunk/etc and /opt/splunk/var are both emptyDir, per #201, leaving all of that data to be stored on the root filesystem of the Kubernetes worker node (in my case, anyway).  My worker nodes are provisioned with SMALL filesystems: 16 GiB, of which approx 11 GiB is in use.

The workaround is simply allocating more disk space to my Kubernetes workers for emptyDir use.

I'd like to see more flexibility from the Splunk Operator in allowing use of /opt/splunk/etc and /opt/splunk/var PVCs for the monitoring console, just as the other Splunk pod types already do.  The monitoring console CRD mentioned in #189 and #346 may address this.

**Comment by pogdin** [comment]
Thanks for your comment.  Yes, please keep watch over the next few months for the Monitoring Console CRD.

**Comment by akondur** [comment]
Fixed with the monitoring console CRD in the upcoming release.
