### ISSUE TITLE
Chart upgrade deletes pvc?

### ISSUE THREAD

**Issue by Frontarolli** [splunk/splunk-operator#537]
Hi.
I'm in the process of upgrade the chart from 0.1.0 to 1.0.0 and the application from 8.1.2 to 8.1.3
Does anyone know if the Splunk PVCs are deleted after chart and application upgrade?

**Comment by akondur** [comment]
Closing the issue per the [comment](https://github.com/splunk/splunk-operator/issues/537#issuecomment-938052121).
