### ISSUE TITLE
No resources (limits/requests) set/configurable for app framework init containers

### ISSUE THREAD

**Issue by BGrasnick** [splunk/splunk-operator#556]
Hey all,

we recently switched to deploy splunk apps using the new Operator App Management Framework and so far it works great regarding app deployment!

However, no resources are set by default and also they are not configurable for the init containers that perform the download from S3. 
This is crucial in our use case as we have multiple Splunk environments in one Kubernetes cluster that scale Heavy Forwarders (based on Standalone CR), clustered Search Heads and clustered Indexers depending on load by using Horizontal Pod Autoscalers but we want to limit the amount of resources consumed by the different Splunk environments.
Therefore, we set resources for our Standalone-HF, ClusterMaster, IndexerCluster and SearchHeadCluster. After switching to the new Operator App Management Framework only the search heads start but everything else including the SearchHeadDeployer do not start because they want to download apps using the initContainers but they have no resources set so the ResourceQuota we have on the namespace blocks their creation.

After looking at the source code a bit, I guess a fix could be employing something similar like [here](https://github.com/splunk/splunk-operator/blob/f803e2dfc10d7852986b92c1f7b080af734964e8/pkg/splunk/enterprise/util.go#L444) in lines 444 to 453 in the same file in the [definition of the container for func setupAppInitContainers ](https://github.com/splunk/splunk-operator/blob/92fef2214efd963363b2bd9c6a34ea5c8e70ae59/pkg/splunk/enterprise/util.go#L922).

Is this possible to be implemented and if so quickly? It is a crucial need for our use case and usage of the splunk-operator.

Thank you already in advance!

**Comment by pogdin** [comment]
Hi @BGrasnick, we're going to move away from init containers over the next few releases of Operator.  I realize that does not solve your immediate problem here but we've found a way to do the app install without needing them.  Thanks.

**Comment by akondur** [comment]
Closing the issue as init container is not used in the latest [release](https://github.com/splunk/splunk-operator/releases/tag/1.1.0).

**Comment by adamrushuk** [comment]
@pogdin I've got issues with the init containers used for the app framework and MinIO - is the new method available to try?

**Comment by akondur** [comment]
Hi @BGrasnick @adamrushuk , Closing the issue since the 2.0.0 release has a newer version of the AppManagement Framework which does not use init containers.
