### ISSUE TITLE
unable to build from dev on uptodate OS (mac)

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#559]
make package causesthe following error
deploy/olm-catalog/splunk/*/
LAST RELEASE VERSION :: 1.0.3
Error: unknown command "w" for "yq"
Run 'yq --help' for usage.
make: *** [generate] Error 1

yq (https://github.com/mikefarah/yq/) version 4.13.5 does not have a w option

**Comment by akondur** [comment]
Hi @rfaircloth-splunk , for running the `make package` command we recommend using the following yq version:

`$ yq -V`
`yq version 3.2.1`
