### ISSUE TITLE
unable to enable ssl on indexer cluster

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#56]
While it might generally be ok to accept s2s communication among nodes in a deployment within k8s because of network protections such as weave. External exposure requires SSL. Enable TLS on additional port and provide the ability to reference a certificate from a k8s secret as the input

**Comment by mikedickey** [comment]
Did you try the [Ingress examples in docs](https://github.com/splunk/splunk-operator/blob/master/docs/Ingress.md)?

**Comment by Caldas** [comment]
@rfaircloth-splunk did the doc solved your problem?

**Comment by Caldas** [comment]
I used cert-manager and it's worked fine @rfaircloth-splunk.

Do you still need help on this or @mikedickey could close?
