### ISSUE TITLE
AppFramework unusable outside of AWS

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#560]
Caused by PR #411 customers with on premise deployments of object storage using external encryption (cni), sidekick or egress service load balancers such as istio can not use the app framework because the customer config is silently modified to a non working value http is being replaced with https.

```
{"level":"info","ts":1635440260.1832197,"logger":"splunk.client.InitMinioClientSession","msg":"Using insecure endpoint, forcing useSSL=true for Minio Client Session","appS3Endpoint":"http://storage-minio.minio.svc.cluster.local:9000"}
```

**Comment by akondur** [comment]
Hi @rfaircloth-splunk , the issue has been resolved via the [PR](https://github.com/splunk/splunk-operator/pull/660/files).
