### ISSUE TITLE
Helm chart deployment for operator

### ISSUE THREAD

**Issue by ryanfaircloth** [splunk/splunk-operator#568]
The current method of deploying operator release or development requires too many steps. Please provide a helm chart do deploy operator correct as single namespace OR cluster wide

**Comment by vzabawski** [comment]
Having an official Helm chart would be nice.

**Comment by adamrushuk** [comment]
I know Boyang was working on this as he reached out to me via email, but know the address is bouncing back. @pogdin is the Helm Chart still in development, and if so, is there a way we can test it and provide feedback?

**Comment by vivekr-splunk** [comment]
Hello @adamrushuk we are working on helm chart for splunk operator. we will soon have something to share.

**Comment by adamrushuk** [comment]
Thanks @vivekr-splunk, I'll look out for that soon then 👍🏼

**Comment by adamrushuk** [comment]
> @adamrushuk any status update for the Helmchart of the Splunk Operator?

I've heard nothing yet from the Splunk guys @markusspitzli

**Comment by pogdin** [comment]
Delivered in [2.1.0](https://github.com/splunk/splunk-operator/blob/main/docs/ChangeLog.md#210-2022-11-22)
