### ISSUE TITLE
inputs should not be enabled on cluster master (or any non indexer role)

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#57]
[splunk@splunk-tail001-cluster-master-0 splunk]$ cat /opt/splunk/etc/system/local/inputs.conf

[splunktcp://9997]
disabled = 0

**Comment by Caldas** [comment]
Great @rfaircloth-splunk .. really needed @mikedickey

**Comment by Caldas** [comment]
@mikedickey just to inform that **License** role also need this

**Comment by felipesewaybricker** [comment]
Same problem here.

**Comment by pogdin** [comment]
I verified no network ports open on Cluster Master, License Master, Deployer, Monitoring Console, Standalone Search Head, Search Head Cluster member.  I will close this if you are observing the same.  Thanks.
