### ISSUE TITLE
splunk enterprise.com/v3 is not available

### ISSUE THREAD

**Issue by dhanasekar79** [splunk/splunk-operator#570]
Hi,

I am trying to download the latest CRD's and updating the cluster configuration as per the documentation. However, the enterprise.com/v3 is not part of the operator CRD's installation and the MonitoringConsole, Indexer and Cluster CR's using enterprise.com/v3 is failing as they are not available as part of the latest CRD's.

**Comment by pogdin** [comment]
Hi, I believe you are looking at the develop branch.  Please use the master branch for the current 1.0.3 release.

**Comment by dhanasekar79** [comment]
Thanks @pogdin . Master branch CRD's doesn't have the package for v3  version as detailed in the documentation.

**Comment by pogdin** [comment]
That's right, v3 is coming in 1.0.4 which is in develop and the develop docs.  Please use 1.0.3 and v2 that is in master and the master docs.

**Comment by dhanasekar79** [comment]
Thanks @pogdin

**Comment by dhanasekar79** [comment]
It worked
