### ISSUE TITLE
S2S/HEC enabled on indexer before first bundle causes data loss

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#58]
The current deployment uses ansible to enable inputs in etc/system/local this is dangerous because when scaling or simply a race condition the indexer will not be aware of its indexes and data will be lost when in an indexer cluster no more should be configured than is required to join the cluster. The master apps folder must be used to push inputs.conf

**Comment by mikedickey** [comment]
Moving this to splunk-ansible https://github.com/splunk/splunk-ansible/issues/439
