### ISSUE TITLE
Monitoring Console not created automatically for Standalone as of 1.0.3

### ISSUE THREAD

**Issue by BGrasnick** [splunk/splunk-operator#580]
I saw that a new Monitoring Console Custom Resource is being created but it is not officially released yet as of splunk operator 1.0.3.
However, in a deployment using said release and splunk:8.2.2 with only a Standalone deployed, no Monitoring Console is deployed anymore.
Why is this? Is there a known fix?

**Comment by kashok-splunk** [comment]
Hi @BGrasnick 
If you are using 1.0.2 Splunk Operator for the k8s release then the monitoring console should be created by default. To give more background of the issue can you please share the operator pod logs, which can give us some information on why the default MC pod is not coming up. MC CRD will be present in the upcoming release and is not a part of the 1.0.2 or 1.0.3 release.

**Comment by pogdin** [comment]
Should still be coming up in 1.0.3 @BGrasnick.  Anything obvious in 
`kubectl logs splunk-operator-xxxxxxxxx-xxxxx | grep error` ?

**Comment by BGrasnick** [comment]
Hey, the problem was actually connected to the App Framework. If you include locations under AppSources that do not contain a splunk app yet, the Standalone successfully starts but no Monitoring Console is created.
