### ISSUE TITLE
Signature mismatch when trying to connect to the license server

### ISSUE THREAD

**Issue by vzabawski** [splunk/splunk-operator#584]
I've deployed Splunk standalone  instance (8.2.2 image) using splunk-operator 1.0.3, and now I'm trying to connect to corporate license manager, but I'm getting the following error:

```
ERROR LMTracker [3297 TcpChannelThread] - failed to send rows, reason='WARN: path=/masterlm/usage: Signature mismatch between license slave=localhost and this License Master. Please make sure that the pass4SymmKey setting in server.conf, under [general], is the same for the License Master and all its slaves from ip=127.0.0.1'
```

I've tried to delete pass4SymmKey from /opt/splunk/etc/system/local/server.conf. After deleting pod, the new pod was created and pass4SymmKey regenerated. The error persisted.
I've created a VM, installed Splunk there, and it connected to the license manager without any problems. Splunk docker container from image 8.2.2 on the same VM connect without any issues. I also tried to connect Splunk in k8s to the VM that is already connected to the license manager, but the error was the same. The config on all those 3 setups was the same, so it seems like something is wrong with the k8s deployment, but I have no ideas where this error comes from.

My environment: 
- AKS cluster (1.20.7)
- splunk/splunk:8.2.2 image
- splunk-operator 1.0.3

If you need any additional information, please let me know.

**Comment by vzabawski** [comment]
The problem was caused by `sslVersions` mismatch between the license manager and my Splunk instance. The error message was misleading though.

**Comment by vzabawski** [comment]
At first, I thought it's caused by `sslVersions`, `sslVersionsForClient`, `cipherSuite` parameters because license manager doesn't work with out of box Splunk configuration, but after adjusting the configuration and reloading it, I still get the error message.

**Comment by vzabawski** [comment]
I ran Splunk in pod and it was able to connect to the license server without any problems, so this issue is reproducible only in Splunk pod deployed by splunk-operator.

Command that I used for running Splunk pod: `kubectl run splunk-test-pod --image=docker.io/splunk/splunk:8.2.2 --env="SPLUNK_PASSWORD=Password@123" --env="SPLUNK_START_ARGS=--accept-license" --port=8000`

**Comment by pogdin** [comment]
Hi @vzabawski , I believe what you are attempting to do is described [here](https://github.com/splunk/splunk-operator/blob/master/docs/Examples.md#using-an-external-license-manager).  When using the Operator, you need to manage certain secrets, like pass4Symmkey, a bit differently than if you were on the filesystem.  Namely, the changes must come from patching/updating the [global secret](https://github.com/splunk/splunk-operator/blob/master/docs/Examples.md#updating-global-kubernetes-secret-object).

**Comment by vzabawski** [comment]
Hi @pogdin. Thanks for a quick reply. I undersand what you are trying to explain, but could you give a bit more details about how this change in behavior may potentially affect the connection to the license manager? Does pass4SymmKey being rewritten by operator from time to time?
I mean, when I deploy Splunk on a VM or in Docker, it generates pass4symmKey on the first run and that's it. I never modified pass4symmKey and never checked if it matches the one on the license manager, it worked out of box, so now I'm a bit confised.
Do I just need to set some random pass4SymmKey in k8s global secret like I already did to the admins' password?

**Comment by vzabawski** [comment]
@pogdin is it possible to bypass the requirement?

> The operator requires that the external LM have a configured pass4SymmKey for authentication.

Our external LM doesn't have pass4symmKey auth enabled, peers are filtered with the firewall.

**Comment by vzabawski** [comment]
Thanks to guys from Splunk community, they helped me to figure out how to fix this issue.
Splunk has default value for `pass4symmKey` out of the box. That means any Splunk instance can connect any other Splunk instance that has default value. Splunk Operator changes out of the box value, so Splunk instance deployed with it can no longer to connect to the Splunk instance with out of the box `pass4symmKey` value. Fixed it by setting default value for `pass4symmKey`.
