### ISSUE TITLE
Splunk operator Deployment sequence issue

### ISSUE THREAD

**Issue by dhanasekar79** [splunk/splunk-operator#592]
Hi,

We would like to retain the PVC volumes created for the splunk resources to retain the log event data. I see the deployment is stuck most of the times due to the sequencing of deployments. Cluster master comes up, followed by indexer, and search head.

Indexer often goes to not ready state and I had to redeploy the cluster master or restart the pod to bring the indexer back to the ready state.

Same goes to search head as it fails during the captain election I had to restart the cluster  master to bring back to the healthy state. Some times the search head resource is stuck with the reconcile process and doesn't go back to the Restart queue.  I had to restart the splunk operator to restart the reconciliation process.

**Comment by pogdin** [comment]
Hi @dhanasekar79, I believe you are looking to capture the Splunk Operator pod logs but let's come back to that.

As the Splunk deployment is provisioning, it is entirely normal to see these requeue and reconciliation messages until all of the pods reach the ready state.  Just as an example, I run a small test deployment in a 2 node EKS cluster.  I bring up my Splunk deployment consisting of a 3 SHC/3 IDXC environment with an LM and HWF, 12 pods total.  I create everything at one time from the same yaml file.  To build this from zero, with the pull of Apps from an S3 bucket takes around 15 minutes.  If you are seeing total failures of pods reaching the ready state and you are having to restart things, something else is wrong.  Check your secrets as I've seen situations where these get out of sync.

The useful logs for troubleshooting the Operator are the Ansible logs and the Operator pod logs themselves.  Trying to capture the whole PVC for each pod in the deployment is not going to give you anything else but the Splunk logs like splunkd, etc.  These are not very helpful.  Furthermore, the Operator pod itself is ephemeral and does not employ a PVC so snapshotting this or like is not possible.  There are a couple of options here.  Most basic, while the Operator pod is running is simply to do

`kubectl logs splunk-operator-xxxxxxxxxx-xxxxx`

and output these to a file.  There are lots of other ways to capture Kubernetes application logs depending on where you are running.  You can use [Splunk Connect for Kubernetes](https://github.com/splunk/splunk-connect-for-kubernetes) and send the logs to any HEC destination.  Most of the public cloud services offer logging as well.  Another option I've used is the [Splunk Add-on for AWS](https://splunkbase.splunk.com/app/1876/). You can send the EKS logs to CloudWatch and then pick them back up into Splunk.

**Comment by dhanasekar79** [comment]
Thanks @pogdin for the details and quick update.

 I have already checked the splunk operator logs and the search head ansible logs. The search head keeps restarting and I can see ansible waiting for peering cluster and it is looking for cluster info from Master. The restart goes in the endless loop. The operator logs shows it keeps reconciling spunk search head  and it never goes to ready state.

The only way to fix the problem is to delete the cluster master and re-create it and then recreate/restart the search head cluster.

Next time if it occurs, I will come up with the proper logs for troubleshooting.

**Comment by pogdin** [comment]
Sounds good @dhanasekar79.  If you are comfortable posting your operator yaml used to create the SHC and CM, please do so as well.
