### ISSUE TITLE
Operator should support the automatic creation of at minimum one HEC token and configuration of HEC

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#6]
Operator should support the configuration and storage of the first HEC token as a secret similar to the default admin password this is valuable for automation of splunk connect for kubernettes

**Comment by mikedickey** [comment]
It does automatically generate a `hec_token` secret and plug it into config, but not sure if the format is ideal.

```
$ kubectl get secret splunk-dfscluster-secrets -o jsonpath='{.data.hec_token}' | base64 --decode
~j?vX+9szdgU)2S?hL~lZZ^M%
```

**Comment by mikedickey** [comment]
v0.0.6 uses UUID style secret for hec_token
