### ISSUE TITLE
Support for multiple container runtime

### ISSUE THREAD

**Issue by dadux** [splunk/splunk-operator#61]
Hi,

In a Kubernetes cluster running `containerd` or `CRI-O`, the containers won't start due to a dependency to docker daemon.

I've raised the issue where the problem lies, https://github.com/splunk/splunk-ansible/issues/431 

I would be keen on suggestion for a workaround in the meantime, i.e. mounting a volume with an empty file `/.dockerfile` in each container would solve the problem ?

Thanks,

**Comment by dadux** [comment]
Actually - this should really not be fixed with splunk-operator and any workaround.

I'll see if I can get it fixed properly either in `splunk-docker` or `splunk-ansible`. 

Closing.

**Comment by mikedickey** [comment]
I'm not aware of any dependencies on docker daemon. In fact, I use operator to run docker-splunk in several k8s clusters that use containerd and CRI-O.

**Comment by dadux** [comment]
@mikedickey - I believe it broke 3 days ago with the latest release of the docker image (8.0.3) - it works just fine with 8.0.2

It's an Ansible problem.
