### ISSUE TITLE
Select image via shared configuration

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#64]
The image version should be pulled from a shared config map or new KIND . In the current implementation on a node failure, the new node pulled a new image for one SHC peer which was newer than the CM image causing a SHC cluster failure. To avoid this "latest/edge" should not be used a specific numbered version should be required and that version should be shared by all related components

**Comment by kelvinatsplunk** [comment]
Right now, the enterprise image version is specified in the operator yaml.  I agree we should put a specific version instead of "latest/edge". I don't think we need a shared config. When we support upgrade, a new KIND with version field may make sense.

**Comment by mikedickey** [comment]
I'm working on a PR that includes pinning it to 8.0.3. Note that 8.0.2 will not work with 0.1.0.
