### ISSUE TITLE
Incorrect configuration of app framework causes crash loop.

### ISSUE THREAD

**Issue by ryanfaircloth** [splunk/splunk-operator#653]
In my case I configured app-framework to use a nonexisting bucket. This leads to a crash loop for the CM. Having the CM not start is potentially desirable as it ensure the CM will be safe to operate by having "golden configs" however when I correct the CM CR operator refused to apply the CR because the CM was "unhealthy". We need some kind of "in between" solution if a PO is broken due to a bad config we need to have the means to fix it other than delete.

**Comment by akondur** [comment]
Hi @ryanfaircloth , closing the issue since it is fixed in the latest release.
