### ISSUE TITLE
Unable to delete unhealthy CR

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#654]
Render a CM unhealthy by invalid config.
Attempt to delete the CM CR observe the deletion hangs on the finalizer.

The desired outcome a deletion should be allowed regardless of the health of the deployment.

**Comment by akondur** [comment]
Hi @rfaircloth-splunk , 

To help investigate further, could you please provide a set of steps to reproduce the issue?

**Comment by sgontla** [comment]
@akondur , I feel this is same scenario like [here](https://github.com/splunk/splunk-operator/issues/569)

**Comment by akondur** [comment]
Hi @rfaircloth-splunk , with the latest develop branch the finalizers should get executed regardless of the health of the deployment based on the explanation provided by @sgontla [here](https://github.com/splunk/splunk-operator/issues/569#issuecomment-1031920965). Could you please re-try on the develop branch image and check if the issue still persists?

**Comment by akondur** [comment]
Closing as per above [comment](https://github.com/splunk/splunk-operator/issues/654#issuecomment-1083480296).
