### ISSUE TITLE
App framework S3 client multiple issues

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#655]
the "minio" client requires tls however there are many use cases where tls would not be desirable such as when minio is deployed to k8s in the same cluster.

the aws s3 client uses a "hack" regex parse to find the region and passes empty string rather than usingthe env var AWS_REGION.

the aws s3 client should allow for a specified region as a new param. The aws s3 client should provide a param to indicate the endpoint should be provided as an argument to the sdk it is currently ignores this is required to support s3 on the edge and third party implementations like ceph

**Comment by atopian** [comment]
This also creates some issues in AKS deployments, see https://github.com/aws/aws-cli/issues/5234

From the above, exposing AWS_EC2_METADATA_DISABLED as a variable will help in EKS/AKS where IMDS is a different implementation

**Comment by atopian** [comment]
Additionally, a debug flag for the aws-cli would be awesome, as this took far longer to chase down without an easy way to increase verbosity in a cluster.

**Comment by lindeskar** [comment]
Just ran into the limitation with `region` being extracted from the endpoint URL. Looks like the regex has "amazonaws.com" hardcoded, which makes using any other S3-compatible service fail?

Any way around this? Setting `AWS_REGION` using `extraEnv` does not apply on the init containers.

**Comment by gaurav-splunk** [comment]
The issue with the `region` field is fixed in this PR: https://github.com/splunk/splunk-operator/pull/700. In upcoming releases, `region` is a configurable parameter in the CR spec.

**Comment by akondur** [comment]
Fixed via the [PR](https://github.com/splunk/splunk-operator/pull/700).
