### ISSUE TITLE
Add support for Taint Tolerations

### ISSUE THREAD

**Issue by terciodemelo** [splunk/splunk-operator#67]
It would be very nice if we had support for `tolerations` in [common spec parameters](https://github.com/splunk/splunk-operator/blob/master/docs/CustomResources.md#common-spec-parameters-for-all-resources) just like `affinity`, this would enable users to leverage [Taints & Toleration](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/) feature in their Splunk clusters as well.

**Comment by Caldas** [comment]
Hey, @mikedickey this is something that we would like to test, so we can group node to SearchHead and Indexers better .. 

Did you like the approach?

**Comment by mikedickey** [comment]
I think it would be quite easy to add pass-through for tolerations, as suggestion.

**Comment by kelvinatsplunk** [comment]
Hi @Caldas @terciodemelo,
Appreciate if you can take a quick look at https://github.com/splunk/splunk-operator/pull/73.

**Comment by Caldas** [comment]
Great @kelvinatsplunk ... I believe you can close this issue 😉
