### ISSUE TITLE
Organization Compliance Requirement to have spec.securityContext.runAsNonRoot=true

### ISSUE THREAD

**Issue by cderocco5** [splunk/splunk-operator#689]
My organization requires that all statefulsets have spec.securityContext.runAsNonRoot=true. There needs to be a way to configure this setting through the CRD to set runAsNonRoot to true. e.g
spec: 
    template:
        spec:
            securityContext:
                 runAsNonRoot: true

**Comment by akondur** [comment]
Hi @cderocco5 , the issue has been fixed via the linked [PR](https://github.com/splunk/splunk-operator/pull/703). 

Currently we are setting the runAsNonRoot to true by default considering that we do not want to run containers as root due to security concerns.
