### ISSUE TITLE
Splunk Master DMC not set up as distributed

### ISSUE THREAD

**Issue by Caldas** [splunk/splunk-operator#69]
Hi, @mikedickey I know you guys already wrote at [README](https://github.com/splunk/splunk-operator/blob/master/docs/README.md#known-issues-for-the-splunk-operator) about **Splunk Master** know issues `The Deployment Monitoring Console is not currently configured properly for new deployments` but I couldn't find an issue relating this 

- [ ] DMC isn't set up to use distributed monitoring when deploying a cluster

**Comment by pogdin** [comment]
@Caldas , we've added this feature into the latest version.  Can you confirm this meets your requirements?  Thanks.

**Comment by pogdin** [comment]
Delivered in 0.2.0 beta
