### ISSUE TITLE
Support use of S2S tokens

### ISSUE THREAD

**Issue by ryanfaircloth** [splunk/splunk-operator#7]
S2S tokens should be used for communication 2 tokens should be created and stored as secrets the first should be used for cluster node to node communication the second for exposed external services

**Comment by akondur** [comment]
Hi @ryanfaircloth , we currently support the programming of multiple [pass4Symmkey](https://github.com/splunk/splunk-operator/blob/master/docs/PasswordManagement.md#pass4symmkey) via password management. Does that resolve the issue of internal and external communication?

**Comment by ryanfaircloth** [comment]
No this is another token entirely it's used by s2s like hec

**Comment by akondur** [comment]
Hi @ryanfaircloth , we currently support injecting defaults via secrets similar to this [comment](https://github.com/splunk/splunk-operator/issues/657#issuecomment-1080967050). Inspecting the spec here we are able to inject s2s in the defaults. Please let me know if this solution works.

**Comment by pogdin** [comment]
CSPL-1578

**Comment by akondur** [comment]
Closing the issue as per the solution mentioned [here](https://github.com/splunk/splunk-operator/issues/7#issuecomment-1117651078).
