### ISSUE TITLE
Master distributed peers missing Splunk cluster components

### ISSUE THREAD

**Issue by Caldas** [splunk/splunk-operator#70]
I just created a new cluster and configured manually the `DMC` at *Splunk Master* to monitor the cluster deployment and to my amazement, the *Search Heads* and the *Deployer* weren't there. So I enter on Distributed Peers list and couldn't find the *Search Heads*, only the *Indexers* were registered.

Need to fix *Deployer* and *Search Heads* registration as Distributed Peers when the enter or leave the cluster

**Comment by mikedickey** [comment]
Splunk Operator currently doesn't configure DMC, but we are working on fixing this.

**Comment by mikedickey** [comment]
Relates to #69

**Comment by Caldas** [comment]
Need to implement it right? I don't know *Go* to I can try to help

**Comment by pogdin** [comment]
Fixed in latest version @Caldas .  Please verify and I will close.
