### ISSUE TITLE
Custom Labels are not getting Assigned to the Pod

### ISSUE THREAD

**Issue by vishnugit24** [splunk/splunk-operator#725]
Hi,

I have installed a Splunk in GKE with custom labels but they are not assigned to the Pod where Splunk is installed. And without the labels the internal service is unable to identify the endpoints. Can you please help me here?

Splunk installation code:
----------------------------
apiVersion: enterprise.splunk.com/v2
kind: Standalone
metadata:
  name: standalonevm
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  selector:
    matchLabels:
      run: standalonevm
      app: standalonevm
  template:
    metadata:
      labels:
        run: standalonevm
------------------------------------
service.yaml
---------------
apiVersion: v1
kind: Service
metadata:
  name: splunkweb
  namespace: default
  labels:
      run: standalonevm
      app: standalonevm
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    run: hfsplunkvm
   app: standalonevm
-----------------------------------
When I created the service.yaml file the endpoints are showing as <none>.

**Comment by vishnugit24** [comment]
Hi @akondur, Thank you the solution is working for me and labels are getting assigned to POD. But when I create the Load balancer service it is unable to identify the endpoints. Can you please tell me how can I make service to identify the endpoints?

----------------
apiVersion: v1
kind: Service
metadata:
  name: splunkweb
  namespace: default
  labels:
    app: splunkvm
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
-----------------------------
kubectl describe svc splunkweb
Name:              splunkweb
Namespace:         default
Labels:            app=splunkvm
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.xxxxxx
IPs:               10.xxxxxxxx
Port:              <unset>  80/TCP
TargetPort:        8000/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>

**Comment by akondur** [comment]
Hi @vishnugit24 , the service `splunkweb` needs to have a selector with labels which will tell it which endpoints to hit. Could you please try this yaml for the service?

```
apiVersion: v1
kind: Service
metadata:
  name: splunkweb
  namespace: default
  labels:
    app: splunkvm
spec:
  - port: 80
     protocol: TCP
     targetPort: 8000
  selector:
    run: hfsplunkvm
    app: standalonevm
```

**Comment by vishnugit24** [comment]
Hi @akondur Thanks for your response, I have executed the same code and still the services are not identifying the endpoint. Please find the below code and output. And please correct me if I am doing something wrong.

SplunkInstallation code:
---------------------------------
apiVersion: enterprise.splunk.com/v2
kind: Standalone
metadata:
  name: hfsplunkvm
  labels:
    app: hfsplunkvm
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  selector:
    matchLabels:
      app: hfsplunkvm
      run: standalone
  template:
    metadata:
      labels:
        app: hfsplunkvm
-----------------------------------
service.yaml
apiVersion: v1
kind: Service
metadata:
  name: splunkweb
  namespace: default
  labels:
    app: hfsplunkvm
spec:
  type: LoadBalancer
  selector:
    app: hfsplunkvm
    run: standalone
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
---------------------------------
service splunkweb output
Name:                     splunkweb
Namespace:                default
Labels:                   app=hfsplunkvm
Annotations:              <none>
Selector:                 app=hfsplunkvm,run=standalone
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.120.x. x
IPs:                      10.120.x.x
LoadBalancer Ingress:     34.85.1xx.xxx
Port:                     <unset>  80/TCP
TargetPort:               8000/TCP
NodePort:                 <unset>  31376/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>

**Comment by akondur** [comment]
Hi @vishnugit24 ,

Here is an example of a simple standalone with a loadBalancer service.

**Standalone**

```
$ cat ~/example_standalone.yml
apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  name: test3
  finalizers:
  - enterprise.splunk.com/delete-pvc /Users/akondur/Desktop/_/imgPullSecrets/splunk-operatorimgPullSecrets

$ kgp splunk-test3-standalone-0 -o yaml | grep -i labels -A 5
  labels:
    app.kubernetes.io/component: standalone
    app.kubernetes.io/instance: splunk-test3-standalone
    app.kubernetes.io/managed-by: splunk-operator
    app.kubernetes.io/name: standalone
    app.kubernetes.io/part-of: splunk-test3-standalone
--
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
--
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - splunk-test3-standalone
```

**Load Balancer Service:**

```
$ cat ~/example_svc.yml
apiVersion: v1
kind: Service
metadata:
  name: splunkweb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/component: standalone
```

**Service has identified endpoints:**

```
$ k describe service/splunkweb
Name:              splunkweb
Namespace:         splunk-operator
Labels:            <none>
Annotations:       Selector:  app.kubernetes.io/component=standalone
Type:              ClusterIP
IP:                10.100.87.69
Port:              <unset>  80/TCP
TargetPort:        8000/TCP
Endpoints:         192.168.4.242:8000
Session Affinity:  None
Events:            <none>
```

In your comment [here](https://github.com/splunk/splunk-operator/issues/725#issuecomment-1100438799), please make sure that the standalone and the service are on the same namespace. The service seems to be on the `default` namespace while the standalone doesn't have a namespace specified(make sure its on the default namespace as well)

**Comment by vishnugit24** [comment]
Thanks @akondur for helping me. Now the services is able to identify the endpoints.
