### ISSUE TITLE
Specify a different service account than the default one

### ISSUE THREAD

**Issue by schen1** [splunk/splunk-operator#74]
So far, the service account used in the statefulsets managed by the CRs is the default service account.

It will be nice to have this customizable.
e.g. using a splunk service account dedicated for Splunk

[Installation on OpenShift](https://github.com/splunk/splunk-operator/blob/master/docs/OpenShift.md) would need to be updated as well.

**Comment by Caldas** [comment]
Agree, this is really needed

**Comment by akondur** [comment]
Hi @Caldas , the latest release of the operator allows the configuration of custom service account in CRDs. See [here](https://github.com/splunk/splunk-operator/blob/master/docs/CustomResources.md#common-spec-parameters-for-splunk-enterprise-resources).
