### ISSUE TITLE
The /opt/splk/etc volume used by initContainer is not defined

### ISSUE THREAD

**Issue by mdaniel** [splunk/splunk-operator#762]
# Summary

In [`pkg/splunk/enterprise/util.go`'s setupInitContainer](https://github.com/splunk/splunk-operator/blob/1.1.0/pkg/splunk/enterprise/util.go#L471) makes reference to a volume named `pvc-etc` that it fails to define

# What happens?

The StatefulSet remains in Pending waiting for the volume to appear

> Warning  FailedCreate  36s (x16 over 3m20s)  statefulset-controller  create Pod splunk-cm-cluster-master-0 in StatefulSet splunk-cm-cluster-master failed error: Pod "splunk-cm-cluster-master-0" is invalid: spec.initContainers[0].volumeMounts[0].name: Not found: "pvc-etc"

# What should happen?

The `setupInitContainer` should inject a `{ name: pvc-etc, emptyDir: {} }` into the `volumes:` of the `PodSpec`

If I had a magic wand, I'd also name that `initc-pvc-etc` since that `/opt/splk/etc` seems to be exclusively used by the `initContainer` and thus `pvc-etc` sounds more generic than in actually is

**Comment by pogdin** [comment]
Thanks @mdaniel.  Two questions. Are you using `ephemeralStorage: true` when observing this and if yes, do you see the same problem without it (using gp2 etc if that is an option).

**Comment by mdaniel** [comment]
I am using `ephemeralStorage:`, yes, but before reporting this I made sure to `git grep splk` to see if my local setup was causing this and the answer appeared to be no, it genuinely was missing

```console
$ git checkout 1.1.0
HEAD is now at be424de4 Merge pull request #732 from splunk/update-release-artifact-upload

$ git grep splk
pkg/splunk/common/paths.go:     OperatorClusterManagerAppsLocal = "/opt/splk/etc/master-apps/splunk-operator/local"
pkg/splunk/common/paths.go:     OperatorClusterManagerAppsLocalIndexesConf = "/opt/splk/etc/master-apps/splunk-operator/local/indexes.conf"
pkg/splunk/common/paths.go:     OperatorClusterManagerAppsLocalServerConf = "/opt/splk/etc/master-apps/splunk-operator/local/server.conf"
pkg/splunk/enterprise/names.go: commandForStandaloneSmartstore = "mkdir -p /opt/splk/etc/apps/splunk-operator/local && ln -sfn  /mnt/splunk-operator/local/indexes.conf /opt/splk/etc/apps/splunk-operator/local/indexes.conf && ln -sfn  /mnt/splunk-operator/local/server.conf /opt/splk/etc/apps/splunk-operator/local/server.conf"
pkg/splunk/enterprise/util.go:                  {Name: "pvc-etc", MountPath: "/opt/splk/etc"},

$ git grep '"pvc-etc"' pkg | grep -v _test.go | grep -v _testingcode.go
pkg/splunk/enterprise/util.go:                  {Name: "pvc-etc", MountPath: "/opt/splk/etc"},
pkg/splunk/test/controller.go:                          {ObjectMeta: metav1.ObjectMeta{Name: "pvc-etc", Namespace: "test"}},
```

**Comment by mdaniel** [comment]
So, to follow up on this, I added the `local-path-provisioner` and you're correct, in that code flow it names the volume `name: pvc-etc`:

```yaml
    - name: pvc-etc
      persistentVolumeClaim:
        claimName: pvc-etc-splunk-cm-cluster-master-0
```

so I guess the accurate ticket description is "please name the ephemeralStorage the same as the PVC one"

**Comment by akondur** [comment]
Fixed with the latest release.
