### ISSUE TITLE
splunk-operator repo missing directory capabilities

### ISSUE THREAD

**Issue by stefanjay** [splunk/splunk-operator#769]
If you are reporting a bug, please include:

    Your operating system name and version
not necessary

    Details about your local setup that might be helpful in troubleshooting (e.g. Kubernetes Version, Container Platform, Ansible version, etc.)

not necessary

    Detailed steps to reproduce the bug
I can't deploy the splunk-operator anymore using this repository on master branch/ tag 1.1.0. Switching to tag 1.0.5 is bringing back the capabilities to deploy the operator and necessary CRDs directly.

e.g. folder `./deploy/` is missing

    We'd also like to hear your feature suggestions. Feel free to submit them as issues by:

    Explaining in detail how they should work
    Keeping the scope as narrow as possible. This will make it easier to implement

Why the directory structure was changed?

**Comment by vivekbasappa** [comment]
Hello @stefanjay, In latest version Splunk operator 1.1.0 deployment steps have been changed. Splunk operator 1.1.0 uses operator-sdk 1.15 and the sdk has simplified deployment steps. 

If you are using source code to deploy please use below command, 
`make deploy IMG=splunk/splunk-operator:1.1.0  SPLUNK_ENTERPRISE_IMAGE=splunk/splunk:8.2.6`

you can also go through documentation here https://github.com/splunk/splunk-operator (section **Deploying the Splunk Operator**) 

if you are using manifest file provided in 1.1.0 release, please use
`kubectl apply -f https://github.com/splunk/splunk-operator/releases/download/1.1.0/splunk-operator-install.yaml`

let me know if you need any further clarification

Thank you

**Comment by stefanjay** [comment]
Hey, thanks for clarification. Was there an announcement about that change? If not be sure that I guess a lot of people struggle with this situation wondering about that. Issue can be closed :)

**Comment by akondur** [comment]
Hi @stefanjay , please find the latest changelog for 1.1.0 release [here](https://github.com/splunk/splunk-operator/blob/master/docs/ChangeLog.md#110-2022-04-12). There is a [link](https://github.com/splunk/splunk-operator/blob/master/docs/SplunkOperatorUpgrade.md) to detailed steps for upgrade mentioned there.

Closing the issue, please re-open if any further help is needed.
