### ISSUE TITLE
Support the automated deployment of Splunk Connect for K8s

### ISSUE THREAD

**Issue by ghost** [splunk/splunk-operator#77]

**Comment by Caldas** [comment]
@themrkeys are you talking about Splunk Connect App?

**Comment by matthewmodestino** [comment]
Splunk Connect for Kubernetes deploy as CRD would be cool. I will also open an separate issue to discuss possible sidecar injection options as well (connect for k8s or UF)

**Comment by eye0fra** [comment]
I agree, would be perfect!

**Comment by akondur** [comment]
Closing this issue as the request will be delivered via a different [project](https://github.com/splunk/splunk-connect-for-kubernetes)
