### ISSUE TITLE
Broken link Nginx Comparison Chart on page Ingress.md

### ISSUE THREAD

**Issue by gjanders** [splunk/splunk-operator#771]
https://github.com/splunk/splunk-operator/blob/develop/docs/Ingress.md
```
NOTE: There are at least 3 flavors of the Nginx Ingress controller.

Kubernetes Ingress Nginx (open source)
Nginx Ingress Open Source (F5's open source version)
Nginx Ingress Plus (F5's paid version)
[Nginx Comparison Chart](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md).
```

The above link is broken, I'm suspecting that https://github.com/nginxinc/kubernetes-ingress/blob/main/docs/content/intro/nginx-ingress-controllers.md might be the correct location...

**Comment by akondur** [comment]
Closing per the [PR](https://github.com/splunk/splunk-operator/pull/776) merge.
