### ISSUE TITLE
Documentation - Examples.md - typo

### ISSUE THREAD

**Issue by gjanders** [splunk/splunk-operator#772]
https://github.com/splunk/splunk-operator/blob/develop/docs/Examples.md#installing-splunk-apps

"To start the monitoring console pod, see [Monitoring Clonsole](https://github.com/splunk/splunk-operator/blob/develop/docs/Examples.md#monitoring-console), or use the example below:"

"Clonsole" is a typo FYI

**Comment by akondur** [comment]
Closing the issue per the [PR](https://github.com/splunk/splunk-operator/pull/775) merge.
