### ISSUE TITLE
Not possible to specify imagePullSecrets

### ISSUE THREAD

**Issue by marcusschiesser** [splunk/splunk-operator#785]
The [spec parameters for all resources](https://splunk.github.io/splunk-operator/CustomResources.html#common-spec-parameters-for-all-resources) allow to specify an own image but don't allow to specify `imagePullSecrets`. Therefore the pods created by the operator can't pull images from a private repository.

The current workaround is to add the `imagePullSecrets` to the service account of the namespace the resource is deployed to:
```
kubectl patch serviceaccount default \
  -p "{\"imagePullSecrets\": [{\"name\": \"image-pull-secret\"}]}" \
  -n <your-namespace>
```

**Comment by akondur** [comment]
Hi @marcusschiesser , we recently added support for imagePullSecrets configuration via the [PR](https://github.com/splunk/splunk-operator/pull/760). The change will be reflected in the next release.

**Comment by akondur** [comment]
Closing as the fix is available in the latest release.
