### ISSUE TITLE
Readiness and liveness probe failing

### ISSUE THREAD

**Issue by firemage722** [splunk/splunk-operator#823]
Hello. I am currently trying to deploy a distributed splunk cluster based on the example from https://youtu.be/Qlm0VPackh8 . Only thing I do not have is a license manager defined. I understand that this is not required for a test installation. When I deploy the cluster, everything comes up except for the SHC pods. They are in a constant restart loop with readiness and liveness probe failed errors. If I port forward to the SHC service/pods directly I am able to access the splunk web interface, however, it disconnects after a few minutes when the pods restart.

**Comment by pogdin** [comment]
Hi, can you post your SHC yaml?

**Comment by firemage722** [comment]
Certainly @pogdin . I managed to get a developer license which I've added as a configmap. Everything else comes up beside the searchheads being in readiness probe failed state now after applying the license. The error on the pod says terminated, exit code: 137

`apiVersion: enterprise.splunk.com/v3
kind: SearchHeadCluster
metadata:
  name: example
  namespace: splunk
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterMasterRef:
    name: cm
  monitoringConsoleRef:
    name: example_mc
  licenseMasterRef:
    name: example`

**Comment by pogdin** [comment]
Thanks @firemage722 .  I was going to say, try removing the `licenseMasterRef` from the shc yaml prior to having the license.  Since you have a functioning LM now, I would just `kubectl delete shc --all` and rebuild the shc.

**Comment by akondur** [comment]
Hi @firemage722 , did you get a chance to try out the [above suggestion](https://github.com/splunk/splunk-operator/issues/823#issuecomment-1155335505)? Please make sure that the License Master is deployed properly when re-deploying the SHC.

**Comment by akondur** [comment]
Hi @firemage722 , checking in to see if you were able to try out the above suggestion?

**Comment by akondur** [comment]
Closing the issue as the **licenseMasterRef** with SHC has been thoroughly tested via smoke tests and locally. Please re-open if the issue with the relevant ansible logs(`kubectl logs <pod_name>`) if the issue still persists.
