### ISSUE TITLE
How to send the _cluster app to master for the configuration bundle?

### ISSUE THREAD

**Issue by felipesewaybricker** [splunk/splunk-operator#90]
How to send the _cluster "app" with the local/indexers through configmap to master (etc/master-apps/_cluster) to use the configuration bundle.

mostly to have a new index on our indexers.

**Comment by mikedickey** [comment]
Please see[ these docs](https://github.com/splunk/splunk-operator/blob/master/docs/Examples.md#using-apps-for-splunk-configuration) on how to package config into apps that are stored in ConfigMap objects. Once you have your indexes.conf in an app, just have your `IndexerCluster` crd deploy it. It will automatically use cluster master to package and bundle and push it out to all of its indexer peers.

**Comment by felipesewaybricker** [comment]
In fact, what I need is to know how I can send an app (containing an indexes.conf file) to be distributed to the indexers (peers) the moment I send it to the master. Via documentation, it only sends to the etc/apps folder, what I need is to send to etc/master_apps folder.
