### ISSUE TITLE
Common Spec parameters for all resources needs increasing

### ISSUE THREAD

**Issue by f1point2** [splunk/splunk-operator#91]
Deployment constantly failed with example values:

apiVersion: enterprise.splunk.com/v1alpha2
kind: Standalone
metadata:
  name: example
spec:
  imagePullPolicy: Always
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

Increased memory to 2Gi and 4Gi respectively to get it working

**Comment by mikedickey** [comment]
Agreed, that was a really bad example in docs ;)

Fixed docs to match default settings, which are more reasonable.
