### ISSUE TITLE
Openshift - Splunk Operator -Standalone instance stuck on crashloop

### ISSUE THREAD

**Issue by ochoa1** [splunk/splunk-operator#921]
when deploying the splunk standalone instance, it deploys but then crashes and enters a crashloop.

Deployed:
apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  name: s1
  finalizers:
  - enterprise.splunk.com/delete-pvc
EOF
standalone.enterprise.splunk.com/s1 created

Error before pod crashes:

WARNING: No password ENV var. Stack may fail to provision if splunk.password is not set in ENV or a default.yml
[DEPRECATION WARNING]: ALLOW_WORLD_READABLE_TMPFILES option, moved to a per
plugin approach that is more flexible, use mostly the same config will work,
but now controlled from the plugin itself and not using the general constant.
instead. This feature will be removed from ansible-base in version 2.14.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
PLAY [Run default Splunk provisioning] *****************************************
Friday 30 September 2022 17:22:06 +0000 (0:00:00.120) 0:00:00.120 ******
TASK [Gathering Facts] *********************************************************
ok: [localhost]
Friday 30 September 2022 17:22:07 +0000 (0:00:00.912) 0:00:01.033 ******
Friday 30 September 2022 17:22:07 +0000 (0:00:00.035) 0:00:01.068 ******
Friday 30 September 2022 17:22:07 +0000 (0:00:00.100) 0:00:01.168 ******
included: /opt/ansible/roles/splunk_common/tasks/get_facts.yml for localhost
Friday 30 September 2022 17:22:07 +0000 (0:00:00.044) 0:00:01.213 ******
TASK [splunk_common : Set privilege escalation user] ***************************
ok: [localhost]
Friday 30 September 2022 17:22:07 +0000 (0:00:00.024) 0:00:01.237 ******
TASK [splunk_common : Check for scloud] ****************************************
ok: [localhost]
Friday 30 September 2022 17:22:07 +0000 (0:00:00.415) 0:00:01.653 ******
Friday 30 September 2022 17:22:07 +0000 (0:00:00.021) 0:00:01.674 ******
Friday 30 September 2022 17:22:08 +0000 (0:00:00.019) 0:00:01.694 ******
TASK [splunk_common : Check for existing installation] *************************

ok: [localhost]
Friday 30 September 2022 17:21:11 +0000 (0:00:00.299) 0:00:01.983 ******
TASK [splunk_common : Set splunk install fact] *********************************
ok: [localhost]
Friday 30 September 2022 17:21:11 +0000 (0:00:00.024) 0:00:02.008 ******
TASK [splunk_common : Check for existing splunk secret] ************************
fatal: [localhost]: FAILED! => {
"changed": false
}
MSG:
Permission denied
PLAY RECAP *********************************************************************
localhost : ok=6 changed=0 unreachable=0 failed=1 skipped=3 rescued=0 ignored=0
Friday 30 September 2022 17:22:08 +0000 (0:00:00.301) 0:00:02.321 ******
===============================================================================
Gathering Facts --------------------------------------------------------- 0.91s
splunk_common : Check for scloud ---------------------------------------- 0.42s
splunk_common : Check for existing splunk secret ------------------------ 0.30s
splunk_common : Check for existing installation ------------------------- 0.30s
Provision role ---------------------------------------------------------- 0.10s
splunk_common : include_tasks ------------------------------------------- 0.04s
Execute pre-setup playbooks --------------------------------------------- 0.04s
splunk_common : Set splunk install fact --------------------------------- 0.03s
splunk_common : Set privilege escalation user --------------------------- 0.02s
splunk_common : Identify service system (Linux) ------------------------- 0.02s
splunk_common : Set systemd boolean ------------------------------------- 0.02s

**Comment by akondur** [comment]
Closing the issue, please re-open if the issue still persists.
