### ISSUE TITLE
Splunk Operator: Allow App Installation on License Master Instances for ITSI Deployment

### ISSUE THREAD

**Issue by SebastianDeiss** [splunk/splunk-operator#961]
### Please select the type of request

Enhancement

### Tell us more

License Master Instances created by Splunk Operator should allow the installation of Splunk Apps configured in ``defaults.yaml``, because Splunk ITSI requires that ``SA-ITSI-Licensechecker`` and ``SA-UserAccess`` are installed on the license master. For details, please see https://docs.splunk.com/Documentation/ITSI/4.13.2/Install/InstallDD.

**Expected behavior**
The Ansible playbook should download and install apps from URLs provided via ``apps_location`` in ``defaults.yaml``.

**Splunk setup on K8S**
- Splunk Image: docker.io/splunk/splunk:8.2.7-openjdk11
- Splunk Operator 2.0.0
- 1 License Master instance with a Splunk Enterprise and a Splunk ITSI License
- 1 Standalone instance with ITSI

**Reproduction/Testing steps**
- Deploy Splunk Operator
- Deploy License Master with two licenses and provde URLs to apps via ``apps_location`` in ``defaults.yaml`.

Ansible Playbook Log:
```
Thursday 03 November 2022  09:57:08 +0000 (0:00:00.073)       0:01:12.857 *****
FAILED - RETRYING: Install app via REST (5 retries left).
FAILED - RETRYING: Install app via REST (4 retries left).
FAILED - RETRYING: Install app via REST (3 retries left).
FAILED - RETRYING: Install app via REST (2 retries left).
FAILED - RETRYING: Install app via REST (1 retries left).

TASK [splunk_license_master : Install app via REST] ****************************
fatal: [localhost]: FAILED! => {
    "attempts": 5,
    "cache_control": "no-store, no-cache, must-revalidate, max-age=0",
    "changed": false,
    "connection": "Close",
    "content_length": "215",
    "content_type": "text/xml; charset=UTF-8",
    "date": "Thu, 03 Nov 2022 09:57:45 GMT",
    "elapsed": 0,
    "expires": "Thu, 26 Oct 1978 00:00:00 GMT",
    "redirected": false,
    "server": "Splunkd",
    "status": 400,
    "url": "https://127.0.0.1:8089/services/apps/local",
    "vary": "Cookie, Authorization",
    "x_content_type_options": "nosniff",
    "x_frame_options": "SAMEORIGIN"
}

MSG:

Status code was 400 and not [200, 201]: HTTP Error 400: Bad Request

PLAY RECAP *********************************************************************
localhost                  : ok=79   changed=4    unreachable=0    failed=1    skipped=75   rescued=0    ignored=2 
```

The result is that ITSI cannot be licensed and thereforce shows up as IT Essentials Work with limited features.

**K8s environment**
- AKS Kubernetes 1.23.5

**Comment by pogdin** [comment]
Hi @SebastianDeiss, a couple of comments on this.  Per our [docs](https://github.com/splunk/splunk-operator/blob/main/docs/README.md#splunk-apps-installation), ITSI is not supported when using Splunk Operator.  Also, using `apps_location` and the URL-based method for App Install should be considered deprecated and replaced by the [App Framework](https://github.com/splunk/splunk-operator/blob/main/docs/AppFramework.md). Beyond that, the Splunk Enterprise Docker container version cannot be mixed and matched with different versions of the Splunk Operator.  Operator 2.0.0 requires Splunk 9.0.0, not 8.2.7.  You are welcome to continue experimenting of course and let us know if App Framework is not working on the License Manager CRD, which it should be.  Thanks.

**Comment by SebastianDeiss** [comment]
I managed to install ITSI inside the container using the legacy app deployment mechanism with the ``8.2.7-openjdk`` image.
I haven't had a chance to test with the latest release, but what I see on Docker Hub and in the release notes of the Operator looks good, so you can close the issue. Thanks.

**Comment by akondur** [comment]
Closing per the above [comment](https://github.com/splunk/splunk-operator/issues/961#issuecomment-1404991157).
