### ISSUE TITLE
Support password rotation for admin password

### ISSUE THREAD

**Issue by aalokmehta** [splunk/splunk-operator#97]
Many customers require that passwords for privileged users be rotated every 30, 60, or 90 days.
The `admin` user of splunk would need to be rotated as such.

The ask here is to support rotation of kubernetes secrets for instances built with operator.

**Comment by matthewmodestino** [comment]
I have seen requests for CyberArk, Vault, 1Password etc as possible integrations to manage the k8s secrets we would pull

**Comment by akondur** [comment]
Hi @aalokmehta , currently we are using a global K8S secret object which can be modified via external integrations such as vault, 1Password. Could you please clarify if this request is for the operator to rotate secrets?

**Comment by akondur** [comment]
Closing as per the [comment](https://github.com/splunk/splunk-operator/issues/97#issuecomment-1086268214)
